---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-pod-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: postgresql
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        USE_WALG_BACKUP: "false"
        USE_WALG_RESTORE: "false"
        CLONE_USE_WALG_RESTORE: "false"
        WAL_S3_BUCKET: "postgresql"
        WAL_BUCKET_SCOPE_PREFIX: ""
        AWS_ACCESS_KEY_ID: "{{ .s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .s3_secret_key }}"
        AWS_S3_FORCE_PATH_STYLE: "true"
        AWS_ENDPOINT: "https://ouranos.mareo.fr:7443"
        BACKUP_SCHEDULE: "00 04 * * *"
