---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: in-cluster-main-cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  teamId: in-cluster
  volume:
    size: 10Gi
    storageClass: csi-rbd-sc-retain
  numberOfInstances: 1

  # users: name -> permissions (usually [])
  users:
    authentik.authentik: []
    gitlab.gitlab: []
    nextcloud.nextcloud: []
    petitstream-dev.petitstream: []
    petitstream.petitstream: []
    vaultwarden.vaultwarden: []

  # databases: name -> owner
  databases:
    authentik: authentik.authentik
    gitlab: gitlab.gitlab
    nextcloud: nextcloud.nextcloud
    petitstream-dev: petitstream-dev.petitstream
    petitstream: petitstream.petitstream
    vaultwarden: vaultwarden.vaultwarden

  postgresql:
    version: "14"

  additionalVolumes:
    - name: pgbackup
      mountPath: /home/postgres/pgbackup
      volumeSource:
        emptyDir: {}

  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: "1"
      memory: 1Gi
