---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-cephfs-secret
  namespace: kube-system
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  template:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
  dataFrom:
    - extract:
        key: ceph-csi/cephfs-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-rbd-secret
  namespace: kube-system
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: ceph-csi/rbd-secret
