# yamllint disable rule:line-length
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: gitlab/object-storage
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        connection: |
          provider: AWS
          region: ceph
          endpoint: "https://athena.mareo.fr:7443"
          path_style: true
          aws_access_key_id: "{{ .s3_client_id | js }}"
          aws_secret_access_key: "{{ .s3_client_secret | js }}"
