---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/
  - postgres

  - authentik-secrets.yml
  - ceph-csi-secrets.yml
  - gitlab-oidc.yml
  - gitlab-saml.yml
  - gitlab-secrets.yml
  - nextcloud-secrets.yml
  - storage-class.yml

patches:
  - target:
      kind: ExternalSecret
    patch: |-
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: unused
      spec:
        target:
          template:
            metadata:
              annotations:
                argocd.argoproj.io/compare-options: IgnoreExtraneous
                argocd.argoproj.io/sync-options: Prune=false
