---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/
  - ../../apps/postgres-operator/
  - dns/
  - hedgedoc
  - ingresses/
  - mail/
  - postgres/
  - secrets/

  - storage-class.yml

patches:
  - patch: |-
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: unused
      spec:
        target:
          template:
            metadata:
              annotations:
                argocd.argoproj.io/compare-options: IgnoreExtraneous
                argocd.argoproj.io/sync-options: Prune=false
    target:
      kind: ExternalSecret
  - patch: |-
      - op: add
        path: /spec/acme/solvers/-
        value:
          selector:
            dnsNames:
              - "vault.mareo.fr"
          http01:
            ingress:
              ingressClassName: public
      - op: add
        path: /spec/acme/solvers/-
        value:
          selector:
            dnsZones:
              - "mareo.fr"
              - "hannache.fr"
              - "theseus.fr"
              - "theseusformations.fr"
              - "theseusformations.com"
          dns01:
            rfc2136:
              nameserver: "mikros.mareo.fr"
              tsigKeyName: "ouranos.mareo.fr."
              tsigAlgorithm: HMACSHA256
              tsigSecretSecretRef:
                name: tsig-secret
                key: mareo.fr
    target:
      kind: ClusterIssuer
      name: default-issuer
