---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/
  - postgres

  - authentik-secrets.yml
  - ceph-csi-secrets.yml
  - gitlab-object-storage.yml
  - gitlab-oidc.yml
  - gitlab-saml.yml
  - gitlab-secrets.yml
  - nextcloud-secrets.yml
  - storage-class.yml

patches:
  - target:
      kind: ExternalSecret
    patch: |-
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: unused
      spec:
        target:
          template:
            metadata:
              annotations:
                argocd.argoproj.io/compare-options: IgnoreExtraneous
                argocd.argoproj.io/sync-options: Prune=false

patchesJson6902:
  - target:
      kind: ClusterIssuer
      name: default-issuer
    patch: |-
      - op: add
        path: /spec/acme/solvers/-
        value:
          selector:
            dnsZone:
              - "mareo.fr"
          dns01:
            rfc2136:
              nameserver: "prometheus.mareo.fr"
              tsigKeyName: "athena.mareo.fr."
              tsigAlgorithm: HMACSHA256
              tsigSecretSecretRef:
                name: tsig-secret
                key: mareo.fr
