---

- name: "Check whether app {{ item.key }} is deployed"
  command:
    argv:
      - argocd
      - --port-forward-namespace
      - argocd
      - --port-forward
      - app
      - get
      - "{{ item.key }}"
  register: app_check
  check_mode: no
  changed_when: false
  failed_when: false

- when: app_check.rc != 0
  block:
    - set_fact:
        command_argv:
          - argocd
          - --port-forward-namespace
          - argocd
          - --port-forward
          - app
          - create
          - "{{ item.key }}"
        command_extra_argv: |
          {% for arg in item.value|dict2items %}
          - "--{{ arg.key|replace('_', '-') }}"
          {% if arg.value is string %}
          - "{{ arg.value }}"
          {% endif %}
          {% endfor %}
    - name: "Add app {{ item.key }}"
      command:
         argv: "{{ command_argv + command_extra_argv|from_yaml }}"
