---
- name: Install radosgw
  ansible.builtin.apt:
    name: radosgw

- name: Check whether radosgw user exists
  ansible.builtin.command:
    argv:
      - ceph
      - auth
      - get
      - client.rgw
  register: result
  failed_when: false
  changed_when: false
  check_mode: false

- name: Create radosgw user
  when: result.rc != 0
  ansible.builtin.command:
    argv:
      - ceph
      - auth
      - get-or-create
      - client.rgw
      - osd
      - allow rwx
      - mon
      - allow rwx
      - -o
      - /etc/pve/priv/ceph.client.rgw.keyring
  changed_when: true

- name: Add configuration for radosgw (host)
  community.general.ini_file:
    path: /etc/pve/ceph.conf
    section: client.rgw
    option: host
    value: "{{ ansible_facts['hostname'] }}"
    mode: "0640"
  notify:
    - Restart radosgw

- name: Add configuration for radosgw (rgw frontends)
  community.general.ini_file:
    path: /etc/pve/ceph.conf
    section: client.rgw
    option: rgw_frontends
    value: "beast port={{ proxmox_ceph_rgw_port }}{% if proxmox_ceph_rgw_sslport %} ssl_port={{ proxmox_ceph_rgw_sslport }} ssl_certificate=/etc/pve/local/pveproxy-ssl.pem ssl_private_key=/etc/pve/local/pveproxy-ssl.key{% endif %}"
    mode: "0640"
  notify:
    - Restart radosgw

- name: Enable radosgw service
  ansible.builtin.service:
    name: ceph-radosgw@rgw
    enabled: true

- name: Create rgw users
  ansible.builtin.include_tasks: ceph_rgw_user.yml
  loop: "{{ proxmox_ceph_rgw_users }}"
