---
- name: Install ansible amazon.aws.s3_bucket dependencies
  ansible.builtin.package:
    name: python3-boto3
    state: present

- name: Getting local storage path
  when: proxmox_ceph_enabled
  block:
    - name: Install Ceph packages
      ansible.builtin.command:
        cmd: pveceph install
        creates: /usr/bin/ceph

    - name: Init Proxmox Ceph cluster
      ansible.builtin.command:
        argv:
          - pveceph
          - init
          - --network
          - "{{ proxmox_ceph_network }}"
          - --cluster-network
          - "{{ proxmox_ceph_cluster_network }}"
          - --size
          - "{{ proxmox_ceph_replicas }}"
        creates: /etc/pve/ceph.conf

    - name: Create mon
      ansible.builtin.command:
        cmd: pveceph mon create
        creates: /etc/pve/priv/ceph.mon.keyring
      retries: 3
      delay: 5
      register: result
      until: result.rc == 0

    - name: Set osd_crush_chooseleaf_type to osd
      community.general.ini_file:
        path: /etc/pve/ceph.conf
        section: global
        option: osd_crush_chooseleaf_type
        value: "0"
        mode: "0640"

    - name: Create OSDs
      ansible.builtin.include_tasks: ceph_osd.yml
      loop: "{{ proxmox_ceph_osds }}"

    - name: Create pools
      ansible.builtin.include_tasks: ceph_pools.yml
      loop: "{{ proxmox_ceph_pools }}"

    - name: Install radosgw
      ansible.builtin.include_tasks: ceph_rgw.yml
      when: proxmox_ceph_rgw_enabled
