---
- name: Get local storage path
  when: proxmox_default_images
  block:
    - name: Get proxmox local storage path from config
      ansible.builtin.shell:
        cmd: "grep -oPz '(?s)dir: {{ proxmox_storage_local }}\\n\\s*path\\s*\\K\\S*' /etc/pve/storage.cfg | tr -cd '[:print:]'"  # noqa: risky-shell-pipe
      register: command_output
      check_mode: false
      changed_when: false
    - name: Set proxmox_local_path
      ansible.builtin.set_fact:
        proxmox_local_path: "{{ command_output.stdout }}"

- name: Ensure default images are present (ISOs)
  ansible.builtin.include_tasks: iso.yml
  with_items: "{{ proxmox_default_images + proxmox_extra_images }}"
  when: proxmox_local_path and item.type == "iso"

- name: Ensure default images are present (templates)
  ansible.builtin.include_tasks: template.yml
  with_items: "{{ proxmox_default_images + proxmox_extra_images }}"
  when: proxmox_local_path and item.type == "template"
