---
- name: Enable forwarding and rp filter (ipv4)
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: true
  loop:
    - net.ipv4.conf.all.forwarding
    - net.ipv4.conf.all.rp_filter

- name: Enable forwarding (ipv6)
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    sysctl_set: true

- name: Configure interfaces
  block:
    - name: Update /etc/network/interfaces
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        block: "{{ lookup('template', 'proxmox-bridges.conf.j2') }}"
        insertafter: EOF
      notify:
        - Reload networking
