# yamllint disable rule:line-length
---

collections:
  - name: community.general
    version: 4.8.6
  - name: community.hashi_vault
    version: 3.3.0
  - name: community.crypto
    version: 2.7.0
  - name: kubernetes.core
    version: 2.3.2
  - name: amazon.aws
    version: 4.2.0

roles:
  - name: ansible-community.ansible-vault
    src: git+https://github.com/ansible-community/ansible-vault.git
    version: 2022.05.01
  - name: xanmanning.k3s
    version: v3.3.0
  - name: ipr-cnrs.nftables
    version: v2.0.1
  - name: bertvv.dhcp
    version: v3.1.0
