# yamllint disable rule:line-length
---
collections:
  - name: community.general
    version: 9.4.0
  - name: community.hashi_vault
    version: 6.2.0
  - name: community.crypto
    version: 2.21.1
  - name: kubernetes.core
    version: 5.0.0
  - name: amazon.aws
    version: 8.1.0

roles:
  - name: ansible-community.ansible-vault
    src: git+https://github.com/ansible-community/ansible-vault.git
    version: 2022.05.01
  - name: xanmanning.k3s
    version: v3.4.4
  - name: ipr-cnrs.nftables
    version: v2.2.1
  - name: bertvv.dhcp
    version: v3.2.0
