# yamllint disable rule:line-length
---
collections:
  - name: community.general
    version: 7.5.1
  - name: community.hashi_vault
    version: 5.0.1
  - name: community.crypto
    version: 2.16.0
  - name: kubernetes.core
    version: 2.4.0
  - name: amazon.aws
    version: 7.0.0

roles:
  - name: ansible-community.ansible-vault
    src: git+https://github.com/ansible-community/ansible-vault.git
    version: 2022.05.01
  - name: xanmanning.k3s
    version: v3.4.2
  - name: ipr-cnrs.nftables
    version: v2.2.1
  - name: bertvv.dhcp
    version: v3.2.0
