# yamllint disable rule:line-length
---
collections:
  - name: community.general
    version: 6.6.0
  - name: community.hashi_vault
    version: 4.2.1
  - name: community.crypto
    version: 2.13.0
  - name: kubernetes.core
    version: 2.4.0
  - name: amazon.aws
    version: 5.5.0

roles:
  - name: ansible-community.ansible-vault
    src: git+https://github.com/ansible-community/ansible-vault.git
    version: 2022.05.01
  - name: xanmanning.k3s
    version: v3.3.1
  - name: ipr-cnrs.nftables
    version: v2.2.1
  - name: bertvv.dhcp
    version: v3.2.0
