---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dovecot-ldap-credentials
  namespace: dovecot
spec:
  dataFrom:
    - extract:
        key: dovecot/ldap-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
