---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: daedalus
  namespace: default
spec:
  endpoints:
    - dnsName: daedalus.theseus.fr
      recordTTL: 3600
      recordType: A
      targets:
        - 95.217.169.229
    - dnsName: daedalus.theseus.fr
      recordTTL: 3600
      recordType: AAAA
      targets:
        - "2a01:4f9:c01e:121::1"
    - dnsName: icarus.daedalus.theseus.fr
      recordTTL: 3600
      recordType: A
      targets:
        - 65.108.238.62
    - dnsName: asterius.daedalus.theseus.fr
      recordTTL: 3600
      recordType: A
      targets:
        - 65.108.238.51
    - dnsName: ariadne.daedalus.theseus.fr
      recordTTL: 3600
      recordType: A
      targets:
        - 65.108.28.147
    - dnsName: '*.apps.daedalus.theseus.fr'
      recordTTL: 3600
      recordType: A
      targets:
        - 95.217.175.227
    - dnsName: '*.apps.daedalus.theseus.fr'
      recordTTL: 3600
      recordType: AAAA
      targets:
        - "2a01:4f9:c01e:19e::1"
