---
galaxy_info:
  author: Marin Hannache
  namespace: mareo
  role_name: argocd
  description: Install ArgoCD
  license: GPLv3
  min_ansible_version: '2.8'
  platforms:
    - name: Debian
    - name: Ubuntu

dependencies: []
