---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: public
  rules:
    - host: api.k8s.mareo.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes
                port:
                  name: https
  tls:
    - hosts:
        - api.k8s.mareo.fr
      secretName: kubernetes-tls
