# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: theseus-openedx
  labels:
    app: openedx
spec:
  project: theseus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: "in-cluster"
    namespace: theseus-openedx
  source:
    repoURL: https://gitlab.mareo.fr/theseus/infrastructure.git
    targetRevision: HEAD
    path: "k8s/openedx"
