---
kind: Kustomization
namespace: postgres-operator

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"

resources:
  - namespace.yml
  - github.com/zalando/postgres-operator/manifests?ref=v1.9.0
  - podmonitor.yml

patchesStrategicMerge:
  - patch-postgres-operator-cm.yml
