# yamllint disable rule:line-length
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
data:
  workers: "1"

  enable_pod_antiaffinity: "true"

  enable_cross_namespace_secret: "true"
  secret_name_template: '{username}.{cluster}.credentials'

  enable_crd_validation: "true"
  enable_lazy_spilo_upgrade: "false"
  enable_shm_volume: "true"

  delete_annotation_date_key: "delete-date"
  delete_annotation_name_key: "delete-clustername"

  additional_pod_capabilities: "SYS_NICE"

  sidecars:
    - name: "exporter"
      image: "prometheuscommunity/postgres_exporter:v0.11.1"
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 200M
      env:
        - name: CLUSTER_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['cluster-name']
        - name: "DATA_SOURCE_URI"
          value: "$(POD_NAME)/postgres?sslmode=require"
        - name: "DATA_SOURCE_USER"
          value: "$(POSTGRES_USER)"
        - name: "DATA_SOURCE_PASS"
          value: "$(POSTGRES_PASSWORD)"
        - name: "PG_EXPORTER_AUTO_DISCOVER_DATABASES"
          value: "true"
        - name: PG_EXPORTER_CONSTANT_LABELS
          value: 'release=$(CLUSTER_NAME),namespace=$(POD_NAMESPACE)'
