---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hedgedoc-object-storage
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: hedgedoc/object-storage
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hedgedoc-openid
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: hedgedoc/authentik-openid
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hedgedoc-session-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: hedgedoc/session-secret
