---
apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petitstream

resources:
  - deployments.yml
  - ingresses.yml
  - namespace.yml
  - secrets.yml
  - services.yml

replicas:
  - name: petitstream-frontend
    count: 1
  - name: petitstream-backend-master
    count: 1
  - name: petitstream-backend-worker
    count: 1

patches:
  - target:
      kind: ExternalSecret
    patch: |-
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: unused
      spec:
        target:
          template:
            metadata:
              annotations:
                argocd.argoproj.io/compare-options: IgnoreExtraneous
                argocd.argoproj.io/sync-options: Prune=false
