---
apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petitstream

resources:
  - ../base/

  - namespace.yml

replicas:
  - name: petitstream-frontend
    count: 1
  - name: petitstream-backend-master
    count: 1
  - name: petitstream-backend-worker
    count: 1

images:
  - name: petitstream/petitstream.com
    newTag: v1.0.0

configMapGenerator:
  - name: petitstream-config
    literals:
      - NODE_ENV=production
      - ORIGIN=https://petitstream.com
      - DATABASE_DB=petitstream
      - DATABASE_HOST=in-cluster-main-cluster.postgres.svc.cluster.local

patches:
  - path: patch-db-creds.yml
    target:
      kind: Deployment
      name: petitstream-backend-master
  - path: patch-db-creds.yml
    target:
      kind: Deployment
      name: petitstream-backend-worker
  - path: patch-ingresses.yml
    target:
      kind: Ingress
