---
apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petitstream

resources:
  - deployments-dev.yml
  - deployments-prod.yml
  - ingresses-dev.yml
  - ingresses-prod.yml
  - namespace.yml
  - secrets.yml
  - services.yml
