---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    creationPolicy: Merge
    deletionPolicy: Merge
  dataFrom:
    - extract:
        key: argocd/webhooks
