---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    creationPolicy: Merge
    deletionPolicy: Merge
  dataFrom:
    - extract:
        key: argocd/webhooks
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-gitlab-mareo-fr-iac-infrastructure
  namespace: argocd
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://gitlab.mareo.fr/iac/infrastructure.git
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: argocd/repositories/iac-infrastructure
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-gitlab-mareo-fr-iac-petitstream
  namespace: argocd
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://gitlab.mareo.fr/iac/petitstream.git
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: argocd/repositories/iac-petitstream
