# yamllint disable rule:line-length
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tsig-secret
  namespace: external-dns
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: rfc2136_tsig_secret
      remoteRef:
        key: cert-manager/tsig
        property: mareo.fr
