---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: factorio-server
  namespace: factorio
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: game_password
      remoteRef:
        key: factorio/server
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: factorio-rcon
  namespace: factorio
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: factorio/rcon
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: factorio-account
  namespace: factorio
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: factorio/account
