# yamllint disable rule:line-length
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foundry-s3
  namespace: foundry
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: foundry/s3
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        aws-credentials.json: |
          {
            "region": "ceph",
            "endpoint": "https://ouranos.mareo.fr:7443",
            "forcePathStyle": true,
            "credentials": {
              "accessKeyId": "{{ .access_key | js }}",
              "secretAccessKey": "{{ .secret_key | js }}"
            }
          }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foundry-secret
  namespace: foundry
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: foundry/secret
