# yamllint disable rule:line-length
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: gitlab/object-storage
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        connection: |
          provider: AWS
          region: ceph
          endpoint: "https://ouranos.mareo.fr:7443"
          path_style: true
          aws_access_key_id: "{{ .s3_access_key | js }}"
          aws_secret_access_key: "{{ .s3_secret_key | js }}"
        s3cfg: |
          [default]
          access_key = {{ .s3_access_key | js }}
          secret_key = {{ .s3_secret_key | js }}
          check_ssl_certificate = True
          guess_mime_type = True
          host_base = ouranos.mareo.fr:7443
          host_bucket = ouranos.mareo.fr:7443
          use_https = True
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-cache-s3
  namespace: gitlab
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: gitlab/object-storage
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        accesskey: "{{ .s3_access_key | js }}"
        secretkey: "{{ .s3_secret_key | js }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: gitlab/object-storage
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        storage: |
          s3:
            bucket: gitlab-registry
            region: ceph
            regionendpoint: "https://ouranos.mareo.fr:7443"
            accesskey: "{{ .s3_access_key | js }}"
            secretkey: "{{ .s3_secret_key | js }}"
