# yamllint disable rule:line-length
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-oidc-authentik
  namespace: gitlab
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: gitlab/oidc-authentik
  target:
    template:
      engineVersion: v2
      type: Opaque
      data:
        provider: |
          {
            "name": "openid_connect",
            "label": "authentik (OIDC)",
            "icon": "https://auth.mareo.fr/static/dist/assets/icons/icon.png",
            "args": {
              "name": "openid_connect",
              "scope": ["openid", "profile", "email"],
              "response_type": "code",
              "issuer": "https://auth.mareo.fr/application/o/gitlab-oidc/",
              "discovery": true,
              "client_auth_method": "query",
              "uid_field": "username",
              "client_options": {
                "identifier": "{{ .client_id | js }}",
                "secret": "{{ .client_secret | js }}",
                "redirect_uri": "https://gitlab.mareo.fr/users/auth/openid_connect/callback",
                "gitlab": {
                  "groups_attribute": "groups",
                  "admin_groups": ["gitlab_admins"],
                  "auditor_groups": ["gitlab_auditors"],
                  "external_groups": ["gitlab_externals"]
                }
              }
            }
          }
