# yamllint disable rule:line-length
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oncall-smtp
  namespace: monitoring
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: smtp-password
      remoteRef:
        key: monitoring/grafana/mail
        property: password
