# yamllint disable rule:line-length
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oncall-smtp
  namespace: monitoring
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: smtp-password
      remoteRef:
        key: monitoring/grafana/mail
        property: password
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grafana-oncall-rabbitmq-password
  namespace: monitoring
spec:
  length: 32
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oncall-rabbitmq-password
  namespace: monitoring
spec:
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: password
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grafana-oncall-rabbitmq-password
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grafana-oncall-redis-password
  namespace: monitoring
spec:
  length: 32
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oncall-redis-password
  namespace: monitoring
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grafana-oncall-redis-password
