---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kargo-secrets
  namespace: kargo
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: kargo/git-client
