---
apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager-secrets.yml
  - argo-cd-secrets.yml
  - argo-workflows-secrets.yml
  - authentik-secrets.yml
  - ceph-csi-secrets.yml
  - cert-manager-tsig.yml
  - external-dns-tsig.yml
  - factorio-secrets.yml
  - foundry-secrets.yml
  - gatus-secrets.yml
  - gitlab-object-storage.yml
  - gitlab-oidc.yml
  - gitlab-saml.yml
  - gitlab-secrets.yml
  - grafana-oncall-secrets.yml
  - grafana-secrets.yml
  - loki-secrets.yml
  - nextcloud-secrets.yml
  - paperless-ngx-secrets.yml
  - vaultwarden-secrets.yml
  - vrising-secrets.yml
