---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: initial-account-username
      remoteRef:
        key: nextcloud/initial-account-credentials
        map: username
    - secretKey: initial-account-password
      remoteRef:
        key: nextcloud/initial-account-credentials
        map: password
    - secretKey: smtp-username
      remoteRef:
        key: nextcloud/mail
        map: username
    - secretKey: smtp-password
      remoteRef:
        key: nextcloud/mail
        map: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: nextcloud/redis
