apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: moodle
  namespace: theseus-moodle
spec:
  secretStoreRef:
    name: theseus-backend
    kind: ClusterSecretStore
  data:
    - secretKey: moodle-password
      remoteRef:
        key: moodle/admin-credentials
        property: password
