# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dovecot
  labels:
    app: dovecot
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-dovecot"
      labels:
        app: dovecot
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: mail
      sources:
        - repoURL: https://gitlab.mareo.fr/iac/infrastructure.git
          targetRevision: HEAD
          ref: argocd
        - repoURL: https://gitlab.mareo.fr/iac/infrastructure.git
          targetRevision: HEAD
          path: "k8s/argocd/apps/mail/extra/"
        - repoURL: registry.mareo.fr/services/charts/dovecot
          chart: dovecot
          targetRevision: 0.0.0-10
          helm:
            valueFiles:
              - $argocd/k8s/argocd/apps/mail/values/dovecot.yml
            values: |
              image:
                tag: commit-c2b7e2459e3bc6d046833d3077070ab274e07358
              fullnameOverride: dovecot
