apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts-examples
  labels:
    app: argo-rollouts-examples
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-argo-rollouts-examples"
      labels:
        app: argo-rollouts-examples
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      source:
        repoURL: https://github.com/argoproj/rollouts-demo/
        targetRevision: HEAD
        path: "examples/canary/"
      destination:
        name: "{{name}}"
        namespace: argo-rollouts-examples
