# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  labels:
    app: argo-rollouts
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: "in-cluster"
    namespace: argo-rollouts
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.37.7
    helm:
      values: |
        fullnameOverride: argo-rollouts
        notifications:
          configmap:
            create: false
        dashboard:
          enabled: true
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: default-issuer
              nginx.ingress.kubernetes.io/auth-url: |-
                  http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
              nginx.ingress.kubernetes.io/auth-signin: |-
                  https://argo-rollouts.mareo.fr/outpost.goauthentik.io/start?rd=$escaped_request_uri
              nginx.ingress.kubernetes.io/auth-response-headers: |-
                  Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
              nginx.ingress.kubernetes.io/auth-snippet: |-
                  proxy_set_header X-Forwarded-Host $http_host;
            ingressClassName: public
            hosts:
              - argo-rollouts.mareo.fr
            tls:
              - secretName: argo-rollouts-tls
                hosts:
                  - argo-rollouts.mareo.fr
