apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
  labels:
    app: argo-rollouts
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-argo-rollouts"
      labels:
        app: argo-rollouts
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      source:
        kustomize:
          resources:
            - https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
      destination:
        name: "{{name}}"
        namespace: argo-rollouts
