# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: authentik
  labels:
    app: authentik
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-authentik"
      labels:
        app: authentik
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: authentik
      source:
        repoURL: https://charts.goauthentik.io/
        chart: authentik
        targetRevision: 2022.9.0
        helm:
          releaseName: authentik
          values: |
            ingress:
              enabled: true
              ingressClassName: public
              annotations:
                cert-manager.io/cluster-issuer: default-issuer
              hosts:
                - host: auth.mareo.fr
                  paths:
                    - path: "/"
                      pathType: Prefix
              tls:
                - hosts:
                    - auth.mareo.fr
                  secretName: "authentik-tls"
            authentik:
              error_reporting:
                enabled: false
              postgresql:
                host: in-cluster-main-cluster.postgres.svc.cluster.local
                name: "authentik"
                user: null
              redis:
                  host: authentik-redis.authentik.svc
              email:
                host: athena.mareo.fr
                port: 465
                use_ssl: true
                from: no-reply@auth.mareo.fr
            env:
              AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL: false
              AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME: false
              AUTHENTIK_OUTPOSTS__DISCOVER: false
            envValueFrom:
              AUTHENTIK_SECRET_KEY:
                secretKeyRef:
                  name: authentik-app
                  key: secret_key
              AK_ADMIN_PASS:
                secretKeyRef:
                  name: authentik-app
                  key: bootstrap_password
              AK_ADMIN_TOKEN:
                secretKeyRef:
                  name: authentik-app
                  key: bootstrap_token
              AUTHENTIK_EMAIL__PASSWORD:
                secretKeyRef:
                  name: authentik-mail
                  key: password
              AUTHENTIK_EMAIL__USERNAME:
                secretKeyRef:
                  name: authentik-mail
                  key: username
              AUTHENTIK_POSTGRESQL__USER:
                secretKeyRef:
                  name: authentik.authentik.in-cluster-main-cluster.credentials
                  key: username
              AUTHENTIK_POSTGRESQL__PASSWORD:
                secretKeyRef:
                  name: authentik.authentik.in-cluster-main-cluster.credentials
                  key: password
              AUTHENTIK_REDIS__PASSWORD:
                secretKeyRef:
                  name: authentik-redis
                  key: password
            prometheus:
              serviceMonitor:
                create: true
              rules:
                create: true
