# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: authentik
  labels:
    app: authentik
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-authentik"
      labels:
        app: authentik
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: authentik
      source:
        repoURL: https://charts.goauthentik.io/
        chart: authentik
        targetRevision: 2024.10.4
        helm:
          releaseName: authentik
          valuesObject:
            global:
              env:
                - name: AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL
                  value: "false"
                - name: AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME
                  value: "false"
                - name: AUTHENTIK_OUTPOSTS__DISCOVER
                  value: "false"
                - name: AUTHENTIK_POSTGRESQL__USE_PGBOUNCER
                  value: "true"
                - name: AUTHENTIK_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: authentik-app
                      key: secret_key
                - name: AK_ADMIN_PASS
                  valueFrom:
                    secretKeyRef:
                      name: authentik-app
                      key: bootstrap_password
                - name: AK_ADMIN_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: authentik-app
                      key: bootstrap_token
                - name: AUTHENTIK_EMAIL__PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: authentik-mail
                      key: password
                - name: AUTHENTIK_EMAIL__USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: authentik-mail
                      key: username
                - name: AUTHENTIK_POSTGRESQL__USER
                  valueFrom:
                    secretKeyRef:
                      name: authentik.authentik.in-cluster-main-cluster.credentials
                      key: username
                - name: AUTHENTIK_POSTGRESQL__PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: authentik.authentik.in-cluster-main-cluster.credentials
                      key: password
                - name: AUTHENTIK_REDIS__PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: authentik-redis
                      key: password
            server:
              metrics:
                serviceMonitor:
                  enabled: true
              ingress:
                enabled: true
                ingressClassName: public
                annotations:
                  cert-manager.io/cluster-issuer: default-issuer
                hosts:
                  - auth.mareo.fr
                tls:
                  - hosts:
                      - auth.mareo.fr
                    secretName: "authentik-tls"
            authentik:
              log_level: debug
              error_reporting:
                enabled: false
              postgresql:
                host: in-cluster-main-cluster-pooler.postgres.svc.cluster.local
                name: "authentik"
                user: null
              redis:
                host: authentik-redis.authentik.svc
              email:
                host: smtp.mareo.fr
                port: 465
                use_ssl: true
                from: no-reply@auth.mareo.fr
            prometheus:
              rules:
                enabled: true
