---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cephfs-csi
  labels:
    app: cephfs-csi
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
            subvolumeGroup: k8s.mareo.fr
  template:
    metadata:
      name: "{{name}}-cephfs-csi"
      labels:
        app: cephfs-csi
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: kube-system
      source:
        repoURL: https://ceph.github.io/csi-charts
        chart: ceph-csi-cephfs
        targetRevision: 3.10.1
        helm:
          releaseName: cephfs-csi
          values: |
            fullnameOverride: ceph-csi-cephfs
            cephConfConfigMapName: ceph-config-cephfs
            csiConfig:
              - clusterID: f750781a-463e-4415-bf93-4dcc6d7991ab
                monitors:
                  - 172.31.0.254:6789
                cephFS:
                  subvolumeGroup: {{subvolumeGroup}}
            provisioner:
              replicaCount: 1
            nodeplugin:
              tolerations:
                - operator: Exists
                  effect: "NoSchedule"
                - operator: Exists
                  effect: "NoExecute"
            storageClass:
              name: csi-cephfs-sc-retain
              create: true
              clusterID: f750781a-463e-4415-bf93-4dcc6d7991ab
              fsName: cephfs
              mounter: kernel
              reclaimPolicy: Retain
      ignoreDifferences:
        - group: rbac.authorization.k8s.io
          kind: ClusterRole
          jsonPointers:
            - /rules
