---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  labels:
    app: cert-manager
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-cert-manager"
      labels:
        app: cert-manager
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: cert-manager
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.8.0
        helm:
          parameters:
            - name: installCRDs
              value: "true"
          values: |
            installCRDs: true
            fullnameOverride: cert-manager
            podDnsPolicy: "None"
            podDnsConfig:
              nameservers:
                - "1.1.1.1"
                - "1.0.0.1"
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
            webhook:
              resources:
                requests:
                  cpu: 50m
                  memory: 32Mi
            cainjector:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/validation/openAPIV3Schema/properties/spec/properties/solver/properties/dns01/properties/webhook/properties/config/x-kubernetes-preserve-unknown-fields
            - /spec/validation/openAPIV3Schema/properties/spec/properties/acme/properties/solvers/items/properties/dns01/properties/webhook/properties/config/x-kubernetes-preserve-unknown-fields
