---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  labels:
    app: cert-manager
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-cert-manager"
      labels:
        app: cert-manager
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: cert-manager
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.16.1
        helm:
          values: |
            installCRDs: true
            fullnameOverride: cert-manager
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
            webhook:
              resources:
                requests:
                  cpu: 50m
                  memory: 32Mi
            cainjector:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
            prometheus:
              enabled: true
              servicemonitor:
                enabled: true
