# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator
  labels:
    app: external-secrets-operator
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-external-secrets-operator"
      labels:
        app: external-secrets-operator
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: external-secrets-operator
      source:
        repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: 0.9.8
        helm:
          releaseName: external-secrets-operator
          values: |
            serviceMonitor:
              enabled: true
