# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  labels:
    app: external-dns
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  goTemplate: true
  template:
    metadata:
      name: "{{ .name }}-external-dns"
      labels:
        app: external-dns
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{ .name }}"
        namespace: external-dns
      source:
        repoURL: registry-1.docker.io/bitnamicharts
        path: external-dns
        chart: external-dns
        targetRevision: 8.7.1
        helm:
          releaseName: external-dns
          valuesObject:
            fullnameOverride: external-dns
            txtOwnerId: "ouranos"
            txtPrefix: externaldns-
            domainFilters:
              - mareo.fr
              - hannache.fr
              - theseus.fr
              - daedalus.theseus.fr
              - theseusformation.fr
              - theseusformation.com
            publishHostIP: true
            policy: upsert-only
            sources:
              - crd
              - service
              - ingress
            crd:
              create: true
            provider: rfc2136
            rfc2136:
              host: 164.132.225.201
              zones:
                - mareo.fr
                - hannache.fr
                - theseus.fr
                - daedalus.theseus.fr
                - theseusformation.fr
                - theseusformation.com
              minTTL: 1h
              secretName: tsig-secret
              tsigSecretAlg: hmac-sha256
              tsigKeyname: ouranos.mareo.fr
            metrics:
              serviceMonitor:
                enabled: true
