# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  labels:
    app: external-dns
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
            zone: mareo.fr
          - name: in-cluster
            zone: hannache.fr
          - name: in-cluster
            zone: theseus.fr
          - name: in-cluster
            zone: theseusformation.fr
          - name: in-cluster
            zone: theseusformation.com
  goTemplate: true
  template:
    metadata:
      name: '{{ .name }}-external-dns-{{ .zone | replace "." "-" }}'
      labels:
        app: external-dns
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{.name}}"
        namespace: external-dns
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: external-dns
        targetRevision: 8.0.2
        helm:
          releaseName: external-dns-{{ .zone | replace "." "-" }}
          values: |
            fullnameOverride: external-dns-{{ .zone | replace "." "-" }}
            txtOwnerId: "ouranos"
            txtPrefix: externaldns-
            domainFilters:
              - {{ .zone }}
            publishHostIP: true
            policy: sync
            provider: rfc2136
            rfc2136:
              host: 164.132.225.201
              zone: {{ .zone }}
              minTTL: 1h
              secretName: tsig-secret
              tsigSecretAlg: hmac-sha256
              tsigKeyname: ouranos.mareo.fr
            metrics:
              serviceMonitor:
                enabled: true
