# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: factorio
  labels:
    app: factorio
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-factorio"
      labels:
        app: factorio
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: factorio
      source:
        repoURL: https://sqljames.github.io/factorio-server-charts/
        chart: factorio-server-charts
        targetRevision: 2.3.0
        helm:
          values: |
            fullnameOverride: factorio
            image:
              tag: 2.0.14
            service:
              type: LoadBalancer
              port: 34197
              annotations:
                external-dns.alpha.kubernetes.io/hostname: factorio.mareo.fr.
            persistence:
              enabled: true
              storageClassName: csi-rbd-sc-retain
            account:
              accountSecret: "factorio-account"
            factorioServer:
              save_name: "marais-salants"
              generate_new_save: true
              update_mods_on_start: true
              enable_space_age: true
            mods:
              enabled: false
              portal: []
            serverPassword:
              passwordSecret: "factorio-server"
            server_settings:
              name: "Les marais salants"
              description: "Private Factorio server"
              max_players: 10
              visibility:
                public: false
                lan: false
              only_admins_can_pause_the_game: false
              require_user_verification: true
              ignore_player_limit_for_returning_players: true
            map_gen_settings:
              seed: 4294967295
            rcon:
              external: false
              type: LoadBalancer
              passwordSecret: "factorio-rcon"
            admin_list:
              - "Mareoh"
