# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gatus
  labels:
    app: gatus
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-gatus"
      labels:
        app: gatus
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: gatus
      source:
        repoURL: https://minicloudlabs.github.io/helm-charts
        chart: gatus
        targetRevision: 3.3.5
        helm:
          values: |
            fullnameOverride: gatus
            ingress:
              enabled: true
              ingressClassName: public
              annotations:
                cert-manager.io/cluster-issuer: default-issuer
              hosts:
                - gatus.mareo.fr
              tls:
                - secretName: gatus-tls
                  hosts:
                    - gatus.mareo.fr
            serviceMonitor:
              enabled: true
            config:
              endpoints:
                  # domains
                  - name: "domain - mareo.fr"
                    group: domains
                    url: "https://mareo.fr"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                  - name: "domain - hannache.fr"
                    group: domains
                    url: "https://hannache.fr"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                  # infrastructure
                  - name: Alertmanager
                    group: infrastructure
                    interval: 1m
                    url: "https://grafana.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Authentik
                    group: infrastructure
                    interval: 1m
                    url: "https://auth.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Grafana
                    group: infrastructure
                    interval: 1m
                    url: "https://grafana.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Hashicorp Vault
                    group: infrastructure
                    interval: 1m
                    url: "https://vault.mareo.fr/v1/sys/seal-status"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY].sealed == false"
                  - name: Prometheus
                    group: infrastructure
                    interval: 1m
                    url: "https://prom.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Proxmox
                    group: infrastructure
                    interval: 1m
                    url: "https://athena.mareo.fr:8006/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>athena - Proxmox Virtual Environment</title>*)"
                  # services
                  - name: GitLab
                    group: services
                    interval: 1m
                    url: "https://gitlab.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: HedgeDoc
                    group: services
                    interval: 1m
                    url: "https://hedgedoc.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>HedgeDoc - Collaborative markdown notes</title>*)"
                  - name: nextcloud
                    group: services
                    interval: 1m
                    url: "https://nextcloud.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Vaultwarden
                    group: services
                    interval: 1m
                    url: "https://nextcloud.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title page-title>Bitwarden Web Vault</title>*)"
