# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gatus
  labels:
    app: gatus
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-gatus"
      labels:
        app: gatus
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: gatus
      source:
        # repoURL: https://minicloudlabs.github.io/helm-charts
        # chart: gatus
        # targetRevision: 3.3.5
        repoURL: https://gitlab.mareo.fr/iac/infrastructure.git
        targetRevision: HEAD
        path: "k8s/charts/gatus"
        helm:
          values: |
            fullnameOverride: gatus
            deployment:
              annotateConfigChecksum: false
            ingress:
              enabled: true
              ingressClassName: public
              annotations:
                cert-manager.io/cluster-issuer: default-issuer
              hosts:
                - gatus.mareo.fr
              tls:
                - secretName: gatus-tls
                  hosts:
                    - gatus.mareo.fr
            serviceMonitor:
              enabled: true
            env:
              DISCORD_WEBHOOK:
                valueFrom:
                  secretKeyRef:
                    name: gatus-discord
                    key: webhook
              POSTGRES_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: gatus.gatus.in-cluster-main-cluster.credentials
                    key: username
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: gatus.gatus.in-cluster-main-cluster.credentials
                    key: password
            config:
              storage:
                type: postgres
                path: "postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@in-cluster-main-cluster.postgres.svc.cluster.local/gatus?sslmode=require"
              alerting:
                discord:
                  webhook-url: "${DISCORD_WEBHOOK}"
                  default-alert:
                    enabled: true
                    failure-threshold: 3
                    send-on-resolved: true
              endpoints:
                  # domains
                  - name: "hannache.fr"
                    group: Domains
                    interval: 24h
                    url: "https://hannache.fr"
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  - name: "mareo.fr"
                    group: Domains
                    interval: 24h
                    url: "https://mareo.fr"
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  - name: "phanes.net"
                    group: Domains
                    interval: 24h
                    url: "https://phanes.net"
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  # SSH
                  - name: athena.mareo.fr
                    group: SSH
                    interval: 1m
                    url: "tcp://athena.mareo.fr:2222"
                    conditions: 
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: prometheus.mareo.fr
                    group: SSH
                    interval: 1m
                    url: "tcp://athena.mareo.fr:22"
                    conditions: 
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  # infrastructure
                  - name: Argo CD
                    group: Infrastructure
                    interval: 1m
                    url: "https://argocd.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 700"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>Argo CD</title>*)"
                    alerts:
                      - type: discord
                  - name: Alertmanager
                    group: Infrastructure
                    interval: 1m
                    url: "https://alertmanager.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 700"
                      - "[STATUS] == 200"
                    alerts:
                      - type: discord
                  - name: Authentik
                    group: Infrastructure
                    interval: 1m
                    url: "https://auth.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>authentik</title>*)"
                    alerts:
                      - type: discord
                  - name: DNS - athena.mareo.fr
                    group: Infratructure
                    interval: 30s
                    url: "athena.mareo.fr"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "A"
                    conditions:
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: DNS - prometheus.mareo.fr
                    group: Infratructure
                    interval: 30s
                    url: "prometheus.mareo.fr"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "A"
                    conditions:
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: Grafana
                    group: Infrastructure
                    interval: 1m
                    url: "https://grafana.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>Grafana</title>*)"
                    alerts:
                      - type: discord
                  - name: Hashicorp Vault
                    group: Infrastructure
                    interval: 1m
                    url: "https://vault.mareo.fr/v1/sys/seal-status"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY].sealed == false"
                    alerts:
                      - type: discord
                  - name: Prometheus
                    group: Infrastructure
                    interval: 1m
                    url: "https://prom.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                    alerts:
                      - type: discord
                  - name: Proxmox
                    group: Infrastructure
                    interval: 1m
                    url: "https://athena.mareo.fr:8006/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>athena - Proxmox Virtual Environment</title>*)"
                    alerts:
                      - type: discord
                  - name: Rados REST Gateway
                    group: Infrastructure
                    interval: 1m
                    url: "https://athena.mareo.fr:7443/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*</ListAllMyBucketsResult>*)"
                    alerts:
                      - type: discord
                  # petitstream
                  - name: "Domain"
                    group: Petitstream
                    url: "https://petitstream.com"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  - name: Site - backend
                    group: Petitstream
                    interval: 1m
                    url: "https://petitstream.com/api/get_next_stream_a/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "len([BODY][0].id) > 0"
                    alerts:
                      - type: discord
                  - name: Site - frontend
                    group: Petitstream
                    interval: 1m
                    url: "https://petitstream.com"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>PetitStream</title>*)"
                    alerts:
                      - type: discord
                  # mail
                  - name: mareo.fr
                    group: Mail - MX records
                    interval: 30s
                    url: "8.8.8.8"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "MX"
                    conditions:
                      - "[BODY] == prometheus.mareo.fr."
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: hannache.fr
                    group: Mail - MX records
                    interval: 30s
                    url: "8.8.8.8"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "MX"
                    conditions:
                      - "[BODY] == prometheus.mareo.fr."
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: prometheus.mareo.fr - imap
                    group: Mail - IMAP
                    interval: 1m
                    url: "tcp://prometheus.mareo.fr:143"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: prometheus.mareo.fr - imaps
                    group: Mail - IMAP
                    interval: 1m
                    url: "tls://prometheus.mareo.fr:993"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  - name: athena.mareo.fr - smtp
                    group: Mail - SMTP
                    interval: 1m
                    url: "tcp://athena.mareo.fr:25"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: athena.mareo.fr - submission
                    group: Mail - SMTP
                    interval: 1m
                    url: "starttls://athena.mareo.fr:587"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  - name: athena.mareo.fr - submissions
                    group: Mail - SMTP
                    interval: 1m
                    url: "tls://athena.mareo.fr:465"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  - name: prometheus.mareo.fr - smtp
                    group: Mail - SMTP
                    interval: 1m
                    url: "tcp://prometheus.mareo.fr:25"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: prometheus.mareo.fr - submission
                    group: Mail - SMTP
                    interval: 1m
                    url: "starttls://prometheus.mareo.fr:587"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  - name: prometheus.mareo.fr - submissions
                    group: Mail - SMTP
                    interval: 1m
                    url: "tls://prometheus.mareo.fr:465"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  # services
                  - name: Factorio
                    group: Services
                    interval: 1m
                    url: "udp://factorio.mareo.fr:34197"
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: GitLab - SSH
                    group: Services
                    interval: 1m
                    url: "tcp://gitlab.mareo.fr:22"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: GitLab - UI
                    group: Services
                    interval: 1m
                    url: "https://gitlab.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                    alerts:
                      - type: discord
                  - name: HedgeDoc
                    group: Services
                    interval: 1m
                    url: "https://hedgedoc.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>HedgeDoc - Collaborative markdown notes</title>*)"
                    alerts:
                      - type: discord
                  - name: Nextcloud
                    group: Services
                    interval: 1m
                    url: "https://nextcloud.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 1000"
                      - "[STATUS] == 200"
                    alerts:
                      - type: discord
                  - name: Vaultwarden
                    group: Services
                    interval: 1m
                    url: "https://vaultwarden.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title page-title>Bitwarden Web Vault</title>*)"
                    alerts:
                      - type: discord
