# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gatus
  labels:
    app: gatus
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-gatus"
      labels:
        app: gatus
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: gatus
      source:
        repoURL: https://minicloudlabs.github.io/helm-charts
        chart: gatus
        targetRevision: 3.3.5
        helm:
          values: |
            fullnameOverride: gatus
            ingress:
              enabled: true
              ingressClassName: public
              annotations:
                cert-manager.io/cluster-issuer: default-issuer
              hosts:
                - gatus.mareo.fr
              tls:
                - secretName: gatus-tls
                  hosts:
                    - gatus.mareo.fr
            serviceMonitor:
              enabled: true
            config:
              endpoints:
                  # domains
                  - name: "domain - hannache.fr"
                    group: domains
                    url: "https://hannache.fr"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                  - name: "domain - mareo.fr"
                    group: domains
                    url: "https://mareo.fr"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                  - name: "domain - phanes.net"
                    group: domains
                    url: "https://phanes.net"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                  - name: DNS - athena.mareo.fr
                    group: infratructure
                    interval: 30s
                    url: "athena.mareo.fr"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "A"
                    conditions:
                      - "[DNS_RCODE] == NOERROR"
                  - name: DNS - prometheus.mareo.fr
                    group: infratructure
                    interval: 30s
                    url: "prometheus.mareo.fr"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "A"
                    conditions:
                      - "[DNS_RCODE] == NOERROR"
                  # infrastructure
                  - name: Alertmanager
                    group: infrastructure
                    interval: 1m
                    url: "https://grafana.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 700"
                      - "[STATUS] == 200"
                  - name: Authentik
                    group: infrastructure
                    interval: 1m
                    url: "https://auth.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Grafana
                    group: infrastructure
                    interval: 1m
                    url: "https://grafana.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Hashicorp Vault
                    group: infrastructure
                    interval: 1m
                    url: "https://vault.mareo.fr/v1/sys/seal-status"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY].sealed == false"
                  - name: Prometheus
                    group: infrastructure
                    interval: 1m
                    url: "https://prom.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Proxmox
                    group: infrastructure
                    interval: 1m
                    url: "https://athena.mareo.fr:8006/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>athena - Proxmox Virtual Environment</title>*)"
                  # petitstream
                  - name: "Petitstream - domain"
                    group: petitstream
                    url: "https://petitstream.com"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                  - name: Petitstream - backend
                    group: petitstream
                    interval: 1m
                    url: "https://petitstream.com/api/get_next_stream_a/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "len([BODY][0].id) > 0"
                  - name: Petitstream - frontend
                    group: petitstream
                    interval: 1m
                    url: "https://petitstream.com"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>PetitStream</title>*)"
                  # mails
                  - name: mareo.fr - MX
                    group: infratructure
                    interval: 30s
                    url: "8.8.8.8"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "MX"
                    conditions:
                      - "[BODY] == prometheus.mareo.fr."
                      - "[DNS_RCODE] == NOERROR"
                  - name: hannache.fr - MX
                    group: infratructure
                    interval: 30s
                    url: "8.8.8.8"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "MX"
                    conditions:
                      - "[BODY] == prometheus.mareo.fr."
                      - "[DNS_RCODE] == NOERROR"
                  - name: prometheus.mareo.fr - imap
                    group: mail
                    interval: 1m
                    url: "tcp://prometheus.mareo.fr:143"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                  - name: prometheus.mareo.fr - imaps
                    group: mail
                    interval: 1m
                    url: "tls://prometheus.mareo.fr:993"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                  - name: prometheus.mareo.fr - smtp
                    group: mail
                    interval: 1m
                    url: "tcp://prometheus.mareo.fr:25"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                  - name: prometheus.mareo.fr - submission
                    group: mail
                    interval: 1m
                    url: "starttls://prometheus.mareo.fr:587"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                  - name: prometheus.mareo.fr - submissions
                    group: mail
                    interval: 1m
                    url: "tls://prometheus.mareo.fr:465"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                  # services
                  - name: GitLab
                    group: services
                    interval: 1m
                    url: "https://gitlab.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: HedgeDoc
                    group: services
                    interval: 1m
                    url: "https://hedgedoc.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>HedgeDoc - Collaborative markdown notes</title>*)"
                  - name: Nextcloud
                    group: services
                    interval: 1m
                    url: "https://nextcloud.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 1000"
                      - "[STATUS] == 200"
                  - name: Vaultwarden
                    group: services
                    interval: 1m
                    url: "https://vaultwarden.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > 720h"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title page-title>Bitwarden Web Vault</title>*)"
