# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gatus
  labels:
    app: gatus
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-gatus"
      labels:
        app: gatus
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: gatus
      source:
        # repoURL: https://minicloudlabs.github.io/helm-charts
        # chart: gatus
        # targetRevision: 3.3.5
        repoURL: https://gitlab.mareo.fr/iac/infrastructure.git
        targetRevision: HEAD
        path: "k8s/charts/gatus"
        helm:
          values: |
            fullnameOverride: gatus
            deployment:
              annotateConfigChecksum: false
            ingress:
              enabled: true
              ingressClassName: public
              annotations:
                cert-manager.io/cluster-issuer: default-issuer
                nginx.ingress.kubernetes.io/auth-url: |-
                    http://authentik.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
                nginx.ingress.kubernetes.io/auth-signin: |-
                    https://gatus.mareo.fr/outpost.goauthentik.io/start?rd=$escaped_request_uri
                nginx.ingress.kubernetes.io/auth-response-headers: |-
                    Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
                nginx.ingress.kubernetes.io/auth-snippet: |-
                    proxy_set_header X-Forwarded-Host $http_host;
              hosts:
                - gatus.mareo.fr
              tls:
                - secretName: gatus-tls
                  hosts:
                    - gatus.mareo.fr
            serviceMonitor:
              enabled: true
            envFrom:
              - secretRef:
                  name: gatus-discord
            env:
              POSTGRES_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: gatus.gatus.in-cluster-main-cluster.credentials
                    key: username
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: gatus.gatus.in-cluster-main-cluster.credentials
                    key: password
              CERTIFICATE_EXPIRATION: 480h
              DOMAIN_CHECK_INTERVAL: 24h
              DOMAIN_EXPIRATION: 480h
              DNS_CHECK_INTERVAL: 10s
              HTTP_CHECK_INTERVAL: 15s
              SMTP_CHECK_INTERVAL: 1m
              SSH_CHECK_INTERVAL: 30s
            config:
              metrics: true
              storage:
                type: postgres
                path: "postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@in-cluster-main-cluster-pooler.postgres.svc.cluster.local/gatus?sslmode=require"
              alerting:
                discord:
                  webhook-url: "${DISCORD_WEBHOOK}"
                  default-alert:
                    enabled: true
                    failure-threshold: 2
                    send-on-resolved: true
                  overrides:
                    - group: "Petitstream"
                      webhook-url: "${DISCORD_WEBHOOK_PETITSTREAM}"
              endpoints:
                  # domains
                  - name: "hannache.fr"
                    group: Domains
                    interval: "${DOMAIN_CHECK_INTERVAL}"
                    url: "https://hannache.fr"
                    conditions:
                      - "[DOMAIN_EXPIRATION] > ${DOMAIN_EXPIRATION}"
                    alerts:
                      - type: discord
                  - name: "mareo.fr"
                    group: Domains
                    interval: "${DOMAIN_CHECK_INTERVAL}"
                    url: "https://mareo.fr"
                    conditions:
                      - "[DOMAIN_EXPIRATION] > ${DOMAIN_EXPIRATION}"
                    alerts:
                      - type: discord
                  - name: "phanes.net"
                    group: Domains
                    interval: "${DOMAIN_CHECK_INTERVAL}"
                    url: "https://phanes.net"
                    conditions:
                      - "[DOMAIN_EXPIRATION] > ${DOMAIN_EXPIRATION}"
                    alerts:
                      - type: discord
                  # SSH
                  - name: athena.mareo.fr
                    group: SSH
                    interval: "${SSH_CHECK_INTERVAL}"
                    url: "tcp://athena.mareo.fr:2222"
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: prometheus.mareo.fr
                    group: SSH
                    interval: "${SSH_CHECK_INTERVAL}"
                    url: "tcp://athena.mareo.fr:22"
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  # infrastructure
                  - name: Argo CD
                    group: Infrastructure
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://argocd.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 700"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>Argo CD</title>*)"
                    alerts:
                      - type: discord
                  - name: Alertmanager
                    group: Infrastructure
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://alertmanager.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 700"
                      - "[STATUS] == 200"
                    alerts:
                      - type: discord
                  - name: Authentik
                    group: Infrastructure
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://auth.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>authentik</title>*)"
                    alerts:
                      - type: discord
                  - name: DNS - athena.mareo.fr
                    group: Infrastructure
                    interval: "${DNS_CHECK_INTERVAL}"
                    url: "athena.mareo.fr"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "A"
                    conditions:
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: DNS - athena.mareo.fr
                    group: Infrastructure
                    interval: "${DNS_CHECK_INTERVAL}"
                    url: "athena.mareo.fr"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "A"
                    conditions:
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: DNS - mikros.mareo.fr
                    group: Infrastructure
                    interval: "${DNS_CHECK_INTERVAL}"
                    url: "mikros.mareo.fr"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "A"
                    conditions:
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: DNS - sdns2.ovh.net.
                    group: Infrastructure
                    interval: "${DNS_CHECK_INTERVAL}"
                    url: "sdns2.ovh.net."
                    dns:
                      query-name: "mareo.fr"
                      query-type: "A"
                    conditions:
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: Grafana
                    group: Infrastructure
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://grafana.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 700"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>Grafana</title>*)"
                    alerts:
                      - type: discord
                  - name: Hashicorp Vault
                    group: Infrastructure
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://vault.mareo.fr/v1/sys/seal-status"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY].sealed == false"
                    alerts:
                      - type: discord
                  - name: Prometheus
                    group: Infrastructure
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://prom.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                    alerts:
                      - type: discord
                  - name: Proxmox
                    group: Infrastructure
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://athena.mareo.fr:8006/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>athena - Proxmox Virtual Environment</title>*)"
                    alerts:
                      - type: discord
                  - name: Rados REST Gateway
                    group: Infrastructure
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://athena.mareo.fr:7443/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*</ListAllMyBucketsResult>*)"
                    alerts:
                      - type: discord
                  # petitstream
                  - name: "Domain"
                    group: Petitstream
                    url: "https://petitstream.com"
                    interval: "${DOMAIN_CHECK_INTERVAL}"
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                    alerts:
                      - type: discord
                  - name: Site - backend
                    group: Petitstream
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://petitstream.com/api/get_next_stream_a/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "has([BODY][0].id) == true"
                    alerts:
                      - type: discord
                  - name: Site - frontend
                    group: Petitstream
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://petitstream.com"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>PetitStream</title>*)"
                    alerts:
                      - type: discord
                  # mail
                  - name: mareo.fr
                    group: Mail - MX records
                    interval: 30s
                    url: "8.8.8.8"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "MX"
                    conditions:
                      - "[BODY] == athena.mareo.fr."
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: hannache.fr
                    group: Mail - MX records
                    interval: "${DNS_CHECK_INTERVAL}"
                    url: "8.8.8.8"
                    dns:
                      query-name: "mareo.fr"
                      query-type: "MX"
                    conditions:
                      - "[BODY] == athena.mareo.fr."
                      - "[DNS_RCODE] == NOERROR"
                    alerts:
                      - type: discord
                  - name: athena.mareo.fr - imaps
                    group: Mail - IMAP
                    interval: 1m
                    url: "tls://athena.mareo.fr:993"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                    alerts:
                      - type: discord
                  - name: athena.mareo.fr - smtp
                    group: Mail - SMTP
                    interval: "${SMTP_CHECK_INTERVAL}"
                    url: "tcp://athena.mareo.fr:25"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: athena.mareo.fr - submission
                    group: Mail - SMTP
                    interval: "${SMTP_CHECK_INTERVAL}"
                    url: "starttls://athena.mareo.fr:587"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                    alerts:
                      - type: discord
                  - name: athena.mareo.fr - submissions
                    group: Mail - SMTP
                    interval: "${SMTP_CHECK_INTERVAL}"
                    url: "tls://athena.mareo.fr:465"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                    alerts:
                      - type: discord
                  # services
                  - name: Factorio
                    group: Services
                    interval: 1m
                    url: "udp://factorio.mareo.fr:34197"
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: GitLab - SSH
                    group: Services
                    interval: "${SSH_CHECK_INTERVAL}"
                    url: "tcp://gitlab.mareo.fr:22"
                    client:
                      timeout: 5s
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: GitLab - UI
                    group: Services
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://gitlab.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 700"
                      - "[STATUS] == 200"
                    alerts:
                      - type: discord
                  - name: HedgeDoc
                    group: Services
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://hedgedoc.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title>HedgeDoc - Collaborative markdown notes</title>*)"
                    alerts:
                      - type: discord
                  - name: Nextcloud
                    group: Services
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://nextcloud.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 2500"
                      - "[STATUS] == 200"
                    alerts:
                      - type: discord
                  - name: Syncthing
                    group: Services
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://syncthing.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                  - name: Syncthing (data)
                    group: Services
                    interval: 1m
                    url: "tcp://syncthing.mareo.fr:22000"
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: Syncthing (discovery)
                    group: Services
                    interval: 1m
                    url: "udp://syncthing.mareo.fr:21027"
                    conditions:
                      - "[CONNECTED] == true"
                    alerts:
                      - type: discord
                  - name: Vaultwarden
                    group: Services
                    interval: "${HTTP_CHECK_INTERVAL}"
                    url: "https://vaultwarden.mareo.fr/"
                    conditions:
                      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION}"
                      - "[RESPONSE_TIME] < 500"
                      - "[STATUS] == 200"
                      - "[BODY] == pat(*<title page-title>Bitwarden Web Vault</title>*)"
                    alerts:
                      - type: discord
