# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gatus
  labels:
    app: gatus
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-gatus"
      labels:
        app: gatus
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: gatus
      source:
        repoURL: https://minicloudlabs.github.io/helm-charts
        chart: gatus
        targetRevision: 3.3.5
        helm:
          values: |
            fullnameOverride: gatus
            ingress:
              enabled: true
              ingressClassName: public
              annotations:
                cert-manager.io/cluster-issuer: default-issuer
              hosts:
                - gatus.mareo.fr
              tls:
                - secretName: gatus-tls
                  hosts:
                    - gatus.mareo.fr
            serviceMonitor:
              enabled: true
            config:
              http-default: &https-default
                interval: 1m
                conditions:
                  - "[STATUS] == 200"
                  - "[RESPONSE_TIME] < 500"
                  - "[CERTIFICATE_EXPIRATION] > 720h"
              endpoints:
                  # domains
                  - name: "domain - mareo.fr"
                    group: domains
                    url: "https://mareo.fr"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                  - name: "domain - hannache.fr"
                    group: domains
                    url: "https://hannache.fr"
                    interval: 24h
                    conditions:
                      - "[DOMAIN_EXPIRATION] > 720h"
                  # infrastructure
                  - name: vault
                    <<: *https-default
                    group: infrastructure
                    url: "https://vault.mareo.fr/v1/sys/seal-status"
                    conditions:
                      - "[BODY].sealed == false"
