# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-gitlab"
      labels:
        app: gitlab
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: gitlab
      source:
        repoURL: https://charts.gitlab.io/
        chart: gitlab
        targetRevision: 7.1.1
        helm:
          releaseName: gitlab
          values: |
            upgradeCheck:
              enabled: false
            postgresql:
              install: false
            certmanager:
              install: false
            nginx-ingress:
              enabled: false
            prometheus:
              install: false
            redis:
              install: false
            operator:
              enabled: false
            global:
              hosts:
                domain: mareo.fr
                https: true
              ingress:
                class: public
                configureCertmanager: false
                tls:
                  secretName: gitlab-tls
                annotations:
                   cert-manager.io/cluster-issuer: default-issuer
              shell:
                tcp:
                  proxyProtocol: true
              initialRootPassword:
                secret: gitlab-initial-root-password
                key: password
              redis:
                host: gitlab-redis.gitlab.svc
                password:
                  secret: gitlab-redis
                  key: password
              psql:
                host: in-cluster-main-cluster.postgres.svc.cluster.local
                database: gitlab
                username: gitlab.gitlab
                password:
                  useSecret: true
                  secret: gitlab.gitlab.in-cluster-main-cluster.credentials
                  key: password
              minio:
                enabled: false
              email:
                display_name: "GitLab"
                from: "no-reply@gitlab.mareo.fr"
              smtp:
                enabled: true
                domain: gitlab.mareo.fr
                address: athena.mareo.fr
                port: 465
                tls: true
                authentication: "plain"
                user_name: "gitlab-mail"
                password:
                  secret: "gitlab-mail"
                  key: "password"
              registry:
                bucket: gitlab-registry
              appConfig:
                enableUsagePing: true
                enableSeatLink: false
                usernameChangingEnabled: false
                lfs:
                  enabled: true
                  proxy_download: true
                artifacts:
                  enabled: true
                  proxy_download: true
                terraformState:
                  enabled: true
                dependencyProxy:
                  enabled: true
                object_store:
                  enabled: true
                  proxy_download: true
                  connection:
                    secret: gitlab-object-storage
                    key: connection
                incomingEmail:
                  enabled: true
                  address: "incoming+%{key}@gitlab.mareo.fr"
                  host: athena.mareo.fr
                  port: 993
                  ssl: true
                  user: "gitlab@gitlab.mareo.fr"
                  password:
                    secret: "gitlab-mail"
                    key: "password"
                  mailbox: inbox
                serviceDeskEmail:
                  enabled: true
                  address: "contact+{key}@gitlab.mareo.fr"
                  host: athena.mareo.fr
                  port: 993
                  ssl: true
                  user: "gitlab@gitlab.mareo.fr"
                  password:
                    secret: "gitlab-mail"
                    key: "password"
                  mailbox: inbox
                ldap:
                  preventSignin: false
                  servers:
                    main:
                      label: LDAP
                      host: ak-outpost-gitlab-ldap.authentik.svc
                      port: 389
                      encryption: plain
                      base: "ou=users,dc=gitlab,dc=mareo,dc=fr"
                      active_directory: false
                      bind_dn: cn=gitlab-ldap,ou=users,dc=gitlab,dc=mareo,dc=fr
                      password:
                        secret: gitlab-ldap
                        key: bind_password
                      uid: cn
                      attributes:
                        email: mail
                        name: name
                        username: cn
                      group_base: "ou=groups,dc=gitlab,dc=mareo,dc=fr"
                      admin_group: "gitlab_admins"
                      external_groups:
                        - "gitlab_externals"
                omniauth:
                  enabled: true
                  blockAutoCreatedUsers: false
                  allowSingleSignOn:
                    - saml
                    - openid_connect
                  autoLinkLdapUser: true
                  autoLinkSamlUser: true
                  autoLinkUser: true
                  providers:
                    - secret: gitlab-saml-group
                    - secret: gitlab-saml-authentik
                    - secret: gitlab-oidc-authentik
                  syncProfileAttributes:
                    - name
                    - email
              time_zone: Europe/Paris
              pages:
                enabled: false
                accessControl: true
                host: pages.mareo.fr
                externalHttp: []
                externalHttps: []
              oauth:
                gitlab-pages:
                  authScope: read_api
            gitlab-runner:
              install: true
              runners:
                config: |
                  [[runners]]
                    [runners.kubernetes]
                    image = "ubuntu:18.04"
                    poll_timeout = 300
                    dns_policy = "default"
                    [runners.cache]
                      Type = "s3"
                      Path = "gitlab-runner"
                      Shared = true
                      [runners.cache.s3]
                        ServerAddress = "athena.mareo.fr:7443"
                        BucketName = "gitlab-runner-cache"
                        BucketLocation = "ceph"
                        Insecure = false
                cache:
                  secretName: gitlab-runner-cache-s3
            gitlab:
              gitlab-shell:
                sshDaemon: gitlab-sshd
                config:
                  proxyProtocol: true
              gitaly:
                persistence:
                  enabled: true
                  storageClass: csi-rbd-sc-retain
              webservice:
                ingress:
                  tls:
                    secretName: gitlab-webservice-tls
                    smartcardSecretName: gitlab-smartcard-tls
              kas:
                ingress:
                  tls:
                    secretName: gitlab-kas-tls
              gitlab-pages:
                ingress:
                  tls:
                    secretName: gitlab-pages-tls
              migrations:
                annotations:
                  "helm.sh/hook": "pre-install"
                  "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
              sidekiq:
                minReplicas: 1
                maxReplicas: 1
                resources:
                  limits:
                    memory: 5G
                  requests:
                    cpu: 500m
            registry:
              storage:
                secret: gitlab-registry-storage
                key: storage
              ingress:
                tls:
                  secretName: gitlab-registry-tls
