# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-gitlab"
      labels:
        app: gitlab
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: gitlab
      source:
        repoURL: https://charts.gitlab.io/
        chart: gitlab
        targetRevision: 6.0.1
        helm:
          values: |
            upgradeCheck:
              enabled: false
            postgresql:
              install: false
            certmanager:
              install: false
            nginx-ingress:
              enabled: false
            prometheus:
              install: false
            redis:
              install: false
            operator:
              enabled: false
            global:
              hosts:
                domain: mareo.fr
                https: true
              ingress:
                class: public
                configureCertmanager: false
                annotations:
                   cert-manager.io/cluster-issuer: default-issuer
              shell:
                tcp:
                  proxyProtocol: true
              initialRootPassword:
                secret: gitlab-initial-root-password
                key: password
              redis:
                host: gitlab-redis.gitlab.svc
                password:
                  secret: gitlab-redis
                  key: password
              psql:
                host: in-cluster-main-cluster.postgres.svc.cluster.local
                database: gitlab
                username: gitlab.gitlab
                password:
                  useSecret: true
                  secret: gitlab.gitlab.in-cluster-main-cluster.credentials
                  key: password
              appConfig:
                enableUsagePing: false
                enableSeatLink: false
                usernameChangingEnabled: false
                lfs:
                  enabled: true
                  proxy_download: true
                artifacts:
                  enabled: true
                  proxy_download: true
                terraformState:
                  enabled: true
                dependencyProxy:
                  enabled: true
              time_zone: Europe/Paris
            gitlab-runner:
              install: false
            gitlab:
              gitaly:
                persistence:
                  enabled: true
                  storageClass: csi-rbd-sc-retain
              minio:
                persistence:
                  enabled: true
                  storageClass: csi-rbd-sc-retain
              webservice:
                ingress:
                  tls:
                    secretName: gitlab-tls
                    smartcardSecretName: smartcard-tls
              kas:
                ingress:
                  tls:
                    secretName: kas-tls
            registry:
              ingress:
                tls:
                  secretName: registry-tls
            minio:
              ingress:
                tls:
                  secretName: minio-tls
