# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-ingress-nginx-internal
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: ingress-nginx
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.6.0
    helm:
      values: |
        fullnameOverride: ingress-nginx-internal
        controller:
          electionID: "ingress-nginx-internal-controller-leader"
          watchIngressWithoutClass: false
          ingressClass: "internal"
          ingressClassResource:
            enabled: true
            default: false
            name: "internal"
            controllerValue: "k8s.io/ingress-nginx-internal"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          config:
            enable-real-ip: "true"
            use-http2: "true"
            server-tokens: "false"
          service:
            enableHttp: true
            enableHttps: true
            type: ClusterIP
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
          minAvailable: 1
          replicaCount: 1
