apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git://git.mareo.fr/infrastructure
    targetRevision: HEAD
    path: k8s/ingress/
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
