# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: ingress-nginx
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.1.0
    helm:
      values: |
        fullnameOverride: ingress-nginx
        controller:
          watchIngressWithoutClass: true
          ingressClass: "public"
          ingressClassResource:
            enabled: true
            default: true
            name: "public"
          tcp:
            22: gitlab/gitlab-gitlab-shell:22
          config:
            forwarded-for-header: "true"
            use-http2: "true"
            server-tokens: "false"
            log-format-escape-json: "true"
            log-format-upstream: '{"msec": "$msec", "connection": "$connection", "connection_requests": "$connection_requests", "pid": "$pid", "request_id": "$request_id", "request_length": "$request_length", "remote_addr": "$remote_addr", "remote_user": "$remote_user", "remote_port": "$remote_port", "time_local": "$time_local", "time_iso8601": "$time_iso8601", "request": "$request", "request_uri": "$request_uri", "args": "$args", "status": "$status", "body_bytes_sent": "$body_bytes_sent", "bytes_sent": "$bytes_sent", "http_referer": "$http_referer", "http_user_agent": "$http_user_agent", "http_x_forwarded_for": "$http_x_forwarded_for", "http_host": "$http_host", "server_name": "$server_name", "request_time": "$request_time", "upstream": "$upstream_addr", "upstream_connect_time": "$upstream_connect_time", "upstream_header_time": "$upstream_header_time", "upstream_response_time": "$upstream_response_time", "upstream_response_length": "$upstream_response_length", "upstream_cache_status": "$upstream_cache_status", "ssl_protocol": "$ssl_protocol", "ssl_cipher": "$ssl_cipher", "scheme": "$scheme", "request_method": "$request_method", "server_protocol": "$server_protocol", "pipe": "$pipe", "gzip_ratio": "$gzip_ratio", "http_cf_ray": "$http_cf_ray", "geoip_country_code": "$geoip_country_code"}'
          service:
            externalTrafficPolicy: Local
            enableHttp: true
            enableHttps: true
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
          minAvailable: 1
          replicaCount: 1
        defaultBackend:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
