# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-ingress-nginx-public
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: ingress-nginx
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.2
    helm:
      values: |
        fullnameOverride: ingress-nginx-public
        controller:
          electionID: "ingress-nginx-public-controller-leader"
          watchIngressWithoutClass: true
          allowSnippetAnnotations: true
          ingressClass: "public"
          ingressClassResource:
            enabled: true
            default: true
            name: "public"
            controllerValue: "k8s.io/ingress-nginx-public"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          config:
            enable-real-ip: "true"
            use-http2: "true"
            server-tokens: "false"
          service:
            externalTrafficPolicy: Local
            enableHttp: true
            enableHttps: true
            type: LoadBalancer
            ports:
              http: 30080
              https: 30443
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
          minAvailable: 1
          replicaCount: 1
        tcp:
          30022: gitlab/gitlab-gitlab-shell:22::PROXY
          30843: ingress-nginx/ingress-nginx-public-controller:30443
        defaultBackend:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
