# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  labels:
    app: kube-prometheus-stack
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-kube-prometheus-stack"
      labels:
        app: kube-prometheus-stack
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: kube-prometheus-stack
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        targetRevision: 39.8.0
        helm:
          values: |
            fullnameOverride: kube-prometheus-stack
            grafana:
              defaultDashboardTimezone: Europe/Paris
              ingress:
                enabled: true
                ingressClassName: public
                annotations:
                  cert-manager.io/cluster-issuer: default-issuer
                hosts:
                  - grafana.mareo.fr
                tls:
                  - secretName: grafana-tls
                    hosts:
                      - grafana.mareo.fr
            alertmanager:
              ingress:
                enabled: true
                ingressClassName: public
                annotations:
                  cert-manager.io/cluster-issuer: default-issuer
                hosts:
                  - alertmanager.mareo.fr
                paths:
                  - /
                pathType: Prefix
                tls:
                  - secretName: alertmanager-tls
                    hosts:
                      - alertmanager.mareo.fr
