# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-nextcloud"
      labels:
        app: nextcloud
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: nextcloud
      source:
        repoURL: https://nextcloud.github.io/helm/
        chart: nextcloud
        targetRevision: 2.14.3
        helm:
          releaseName: nextcloud
          values: |
            ingress:
              enabled: true
              className: public
              annotations:
                nginx.ingress.kubernetes.io/proxy-body-size: 4G
                nginx.ingress.kubernetes.io/enable-cors: "true"
                nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
                cert-manager.io/cluster-issuer: default-issuer
              tls:
                - secretName: nextcloud-tls
                  hosts:
                    - nextcloud.mareo.fr
            nextcloud:
              host: nextcloud.mareo.fr
              existingSecret:
                enabled: true
                secretName: nextcloud
                usernameKey: username
                passwordKey: password
            persistence:
              enabled: true
              storage-class: csi-cephfs-sc-retain
              size: 1Ti
            phpClientHttpsFix:
              enabled: true
            cronjob:
              enabled: true
