# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petitstream-dev
  labels:
    app: petitstream-dev
    notifications.argoproj.io/ignore-defaults: "true"
    notifications.argoproj.io/subscribe: "petitstream"
spec:
  project: petitstream
  sources:
    - repoURL: https://gitlab.mareo.fr/iac/petitstream.git
      targetRevision: HEAD
      path: "dev/"
    - repoURL: https://ot-container-kit.github.io/helm-charts/
      chart: redis
      targetRevision: 0.16.1
      helm:
        releaseName: "redis"
        valuesObject:
          redisStandalone:
            redisSecret:
              secretName: "petitstream-redis"
              secretKey: "password"
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: csi-rbd-sc-delete
  destination:
    name: "in-cluster"
    namespace: "petitstream-dev"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
