apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petitstream
  labels:
    app: petitstream
spec:
  project: petitstream
  source:
    repoURL: https://gitlab.mareo.fr/iac/petitstream.git
    targetRevision: HEAD
    path: "prod"
  destination:
    name: "in-cluster"
    namespace: "petitstream"
  syncPolicy:
    automated:
      prune: false
