---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petitstream-dev
  labels:
    app: petitstream-dev
spec:
  project: petitstream
  source:
    repoURL: https://gitlab.mareo.fr/iac/petitstream.git
    targetRevision: HEAD
    path: "dev/"
  destination:
    name: "in-cluster"
    namespace: "petitstream-dev"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
