---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  generators:
    - list:
        elements:
          - name: gitlab
            cluster: in-cluster
            namespace: gitlab
            secretName: gitlab-redis
            secretKey: password
          - name: nextcloud
            cluster: in-cluster
            namespace: nextcloud
            secretName: nextcloud-redis
            secretKey: password
          - name: authentik
            cluster: in-cluster
            namespace: authentik
            secretName: authentik-redis
            secretKey: password
  template:
    metadata:
      name: "{{cluster}}-{{name}}-redis"
      labels:
        app: "{{cluster}}-{{name}}-redis"
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{cluster}}"
        namespace: "{{namespace}}"
      project: default
      source:
        repoURL: https://ot-container-kit.github.io/helm-charts/
        chart: redis
        targetRevision: 0.16.3
        helm:
          releaseName: "{{name}}-redis"
          values: |
            redisStandalone:
              redisSecret:
                secretName: "{{secretName}}"
                secretKey: "{{secretKey}}"
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: csi-rbd-sc-delete
                  resources:
                    requests:
                      storage: 10G
