# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-syncthing"
      labels:
        app: syncthing
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: syncthing
      source:
        repoURL: https://k8s-home-lab.github.io/helm-charts/
        chart: syncthing
        targetRevision: 4.0.0
        helm:
          releaseName: syncthing
          values: |
            service:
              listen:
                type: LoadBalancer
                externalTrafficPolicy: Cluster
              discovery:
                type: LoadBalancer
                externalTrafficPolicy: Cluster
            ingress:
              main:
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: default-issuer
                  nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
                  nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
                  nginx.ingress.kubernetes.io/auth-url: |-
                      http://authentik.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
                  nginx.ingress.kubernetes.io/auth-signin: |-
                      https://syncthing.mareo.fr/outpost.goauthentik.io/start?rd=$escaped_request_uri
                  nginx.ingress.kubernetes.io/auth-response-headers: |-
                      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
                  nginx.ingress.kubernetes.io/auth-snippet: |-
                      proxy_set_header X-Forwarded-Host $http_host;
                ingressClassName: "public"
                hosts:
                  - host: syncthing.mareo.fr
                    paths:
                      - path: /
                tls:
                  - secretName: syncthing-tls
                    hosts:
                      - syncthing.mareo.fr
            persistence:
              data:
                enabled: true
                type: pvc
                storageClass: csi-cephfs-sc-retain
                accessMode: ReadWriteOnce
                size: 500Gi
