---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-secrets-operator
  labels:
    app: vault-secrets-operator
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
            appRolePath: k8s-undercloud
          - name: prod-1
            appRolePath: k8s-prod-1
          - name: ops
            appRolePath: k8s-ops
          - name: assistants-prod-1
            appRolePath: k8s-assistants-prod-1
  template:
    metadata:
      name: "{{name}}-vault-secrets-operator"
      labels:
        app: vault-secrets-operator
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: vault-secrets-operator
      source:
        repoURL: https://ricoberger.github.io/helm-charts
        chart: vault-secrets-operator
        targetRevision: 1.18.0
        helm:
          values: |
            fullnameOverride: vault-secrets-operator
            vault:
              authMethod: approle
              appRolePath: auth/{{appRolePath}}
              reconciliationTime: 60
              address: https://vault.cri.epita.fr
            environmentVars:
              - name: VAULT_ROLE_ID
                valueFrom:
                  secretKeyRef:
                    name: vault-approle
                    key: VAULT_ROLE_ID
              - name: VAULT_SECRET_ID
                valueFrom:
                  secretKeyRef:
                    name: vault-approle
                    key: VAULT_SECRET_ID
              - name: VAULT_TOKEN_MAX_TTL
                valueFrom:
                  secretKeyRef:
                    name: vault-approle
                    key: VAULT_TOKEN_MAX_TTL
            serviceMonitor:
              enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: vaultsecrets.ricoberger.de
          jsonPointers:
            - /metadata/labels
