# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vrising
  labels:
    app: vrising
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-vrising"
      labels:
        app: vrising
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: vrising
      source:
        repoURL: registry.mareo.fr/services/charts/vrising
        chart: vrising
        targetRevision: 0.0.0-1
        helm:
          values: |
            fullnameOverride: vrising
            service:
              type: LoadBalancer
              nodePorts:
                game: 32318
                query: 31101
              annotations:
                external-dns.alpha.kubernetes.io/hostname: vrising.mareo.fr.
            persistence:
              enabled: true
              storageClassName: csi-rbd-sc-retain
            config:
              hostSettings:
                tz: "Europe/Paris"
                saveName: "world"
                password:
                  secret: "vrising-passwords"
              extraHostSettings:
                Name: "La commu de l'anneau"
              gameSettings:
                GameModeType: 0
                CastleDamageMode: 0
                CastleHeartDamageMode: 0
                DeathContainerPermission: 1
                RelicSpawnType: 1
                CanLootEnemyContainers: false
                InventoryStacksModifier: 5.0
                DropTableModifier_General: 4.0
                DropTableModifier_Missions: 4.0
                MaterialYieldModifier_Global: 4.0
                BloodEssenceYieldModifier: 4.0
                CastleMinimumDistanceInFloors: 1
                ClanSize: 20
                BloodDrainModifier: 0.2
                DurabilityDrainModifier: 0.0
                CastleDecayRateModifier: 0.2
                CastleBloodEssenceDrainModifier: 0.2
                AnnounceSiegeWeaponSpawn: false
                CraftRateModifier: 8.0
                RefinementRateModifier: 8.0
                ServantConvertRateModifier: 2.0
                Death_DurabilityFactorLoss: 0.0
                Death_DurabilityLossFactorAsResources: 0.0
                VBloodUnitSettings: []
                UnlockedAchievements: []
                UnlockedResearchs: []
                GameTimeModifiers: {}
                VampireStatModifiers:
                  ResourcePowerModifier: 5.0
                EquipmentStatModifiers_Global:
                  ResourceYieldModifier: 3.0
                CastleStatModifiers_Global:
                  SafetyBoxLimit: 20
                  VerminNestLimit: 8
                  HeartLimits:
                    Level1: {}
                    Level2: {}
                    Level3: {}
                    Level4: {}
                    Level5: {}
                PlayerInteractionSettings:
                  VSPlayerWeekdayTime: {}
                  VSPlayerWeekendTime: {}
                  VSCastleWeekdayTime: {}
                  VSCastleWeekendTime: {}
                TraderModifiers:
                  StockModifier: 5.0
                  PriceModifier: 5.0
                  RestockTimerModifier: 10.0
              adminlist:
                - "76561198035482540"  # mareoh
            rcon:
              external: true
              password:
                secret: "vrising-passwords"
