# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vrising
  labels:
    app: vrising
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "{{name}}-vrising"
      labels:
        app: vrising
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: vrising
      source:
        repoURL: registry.mareo.fr/services/charts/vrising
        chart: vrising
        targetRevision: 0.0.0-1
        helm:
          values: |
            fullnameOverride: vrising
            service:
              type: LoadBalancer
              annotations:
                external-dns.alpha.kubernetes.io/hostname: vrising.mareo.fr.
            persistence:
              enabled: true
              storageClassName: csi-rbd-sc-retain
            config:
              hostSettings:
                tz: "Europe/Paris"
                password:
                  secret: "vrising"
              adminlist:
                - "76561198035482540"  # mareoh
            rcon:
              external: true
              password:
                secret: "vrising"
