# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vrising
  labels:
    app: vrising
spec:
  generators:
    - list:
        elements:
          #- name: in-cluster
  template:
    metadata:
      name: "{{name}}-vrising"
      labels:
        app: vrising
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: vrising
      source:
        repoURL: registry.mareo.fr/services/charts/vrising
        chart: vrising
        targetRevision: 0.0.0-1
        helm:
          valuesObject:
            fullnameOverride: vrising
            service:
              type: LoadBalancer
              nodePorts:
                game: 32318
                query: 31101
              annotations:
                external-dns.alpha.kubernetes.io/hostname: vrising.mareo.fr.
            persistence:
              enabled: true
              storageClassName: csi-rbd-sc-retain
            config:
              hostSettings:
                tz: "Europe/Paris"
                saveName: los_deglingos
                serverName: "Los Deglingos (vrising.mareo.fr)"
                listOnMasterServer: "true"
                gameSettingsPreset: ""
                gameDifficultyPreset: ""
                password:
                  secret: "vrising-passwords"
              gameSettings:
                AnnounceSiegeWeaponSpawn: true
                BloodDrainModifier: 0.1
                BloodEssenceYieldModifier: 4.0
                CanLootEnemyContainers: false
                CastleBloodEssenceDrainModifier: 0.2
                CastleDamageMode: 0
                CastleDecayRateModifier: 0.2
                CastleHeartDamageMode: 0
                CastleMinimumDistanceInFloors: 1
                CastleStatModifiers_Global:
                  CastleLimit: 3
                  HeartLimits:
                    Level1:
                      FloorLimit: 200
                    Level2:
                      FloorLimit: 300
                    Level3:
                      FloorLimit: 400
                      HeightLimit: 4
                    Level4:
                      FloorLimit: 500
                      HeightLimit: 5
                    Level5:
                      FloorLimit: 600
                      HeightLimit: 6
                  SafetyBoxLimit: 20
                  VerminNestLimit: 8
                ClanSize: 20
                CraftRateModifier: 8.0
                DeathContainerPermission: 1
                Death_DurabilityFactorLoss: 0.0
                Death_DurabilityLossFactorAsResources: 0.0
                DropTableModifier_General: 5.0
                DropTableModifier_Missions: 5.0
                DurabilityDrainModifier: 0.0
                EquipmentStatModifiers_Global:
                  ResourceYieldModifier: 3.0
                GameDifficulty: 2
                GameModeType: "PvP"
                GameTimeModifiers: {}
                InventoryStacksModifier: 5.0
                MaterialYieldModifier_Global: 4.0
                PlayerInteractionSettings:
                  VSCastleWeekdayTime: {}
                  VSCastleWeekendTime: {}
                  VSPlayerWeekdayTime: {}
                  VSPlayerWeekendTime: {}
                RefinementRateModifier: 8.0
                RelicSpawnType: 1
                ServantConvertRateModifier: 5.0
                TeleportBoundItems: false
                TraderModifiers:
                  PriceModifier: 1.0
                  RestockTimerModifier: 10.0
                  StockModifier: 5.0
                UnitStatModifiers_Global:
                  MaxHealthModifier: 1
                  PowerModifier: 1.4
                UnitStatModifiers_VBlood:
                  MaxHealthModifier: 1.25
                  PowerModifier: 1.7
                  LevelIncrease: 3
                UnlockedAchievements: []
                UnlockedResearchs: []
                VBloodUnitSettings: []
                VampireStatModifiers:
                  ResourcePowerModifier: 5.0
              adminlist:
                - "76561198015953680"  # Sylvartas
                - "76561198035482540"  # mareoh
                - "76561198021205451"  # Chewie
                - "76561197975736722"  # Compy
            serviceMonitor:
              enabled: true
            api:
              enabled: true
            rcon:
              enabled: true
              password:
                secret: "vrising-passwords"
              enableExperimental: true
