---
apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petitstream

resources:
  - deployments-dev.yml
  - deployments-prod.yml
  - ingresses-dev.yml
  - ingresses-prod.yml
  - namespace.yml
  - secrets.yml
  - services.yml

patches:
  - target:
      kind: ExternalSecret
    patch: |-
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: unused
      spec:
        target:
          template:
            metadata:
              annotations:
                argocd.argoproj.io/compare-options: IgnoreExtraneous
                argocd.argoproj.io/sync-options: Prune=false
