---
apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petitstream-dev

resources:
  - ../base/

  - deployments-dev.yml
  - ingresses-dev.yml
  - namespace.yml

replicas:
  - name: petitstream-frontend
    count: 1
  - name: petitstream-backend-master
    count: 1
  - name: petitstream-backend-worker
    count: 0

