---
apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petitstream-dev

resources:
  - ../base/

  - namespace.yml

replicas:
  - name: petitstream-frontend
    count: 1
  - name: petitstream-backend-master
    count: 1
  - name: petitstream-backend-worker
    count: 0

configMapGenerator:
  - name: petitstream-config
    literals:
      - NODE_ENV=development
      - ORIGIN=https://dev.petitstream.com
      - DATABASE_DB=petitstream_dev
      - DATABASE_HOST=in-cluster-main-cluster.postgres.svc.cluster.local

patches:
  - path: patch-db-creds.yml
    target:
      kind: Deployment
      name: petitstream-backend-master
  - path: patch-db-creds.yml
    target:
      kind: Deployment
      name: petitstream-backend-worker
  - path: patch-ingresses.yml
    target:
      kind: Ingress
