- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DATABASE_USERNAME
    valueFrom:
      secretKeyRef:
        name: petitstream-dev.petitstream-dev.in-cluster-main-cluster.credentials
        key: username
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: petitstream-dev.petitstream-dev.in-cluster-main-cluster.credentials
        key: password
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DATABASE_URL
    value: "postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_DB)"
