# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki
  labels:
    app: loki
spec:
  generators:
    - list:
        elements:
          - name: in-cluster
  goTemplate: true
  template:
    metadata:
      name: "{{.name}}-loki"
      labels:
        app: loki
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: false
      destination:
        name: "{{.name}}"
        namespace: monitoring
      source:
        repoURL: https://grafana.github.io/helm-charts
        chart: loki
        targetRevision: 6.22.0
        helm:
          valuesObject:
            fullnameOverride: loki
            gateway:
              enabled: true
              replicas: 1
              affinity: ""
            loki:
              auth_enabled: false
              commonConfig:
                replication_factor: 1
              storage:
                type: s3
                bucketNames:
                  chunks: loki
                  ruler: loki
                  admin: loki
                s3:
                  endpoint: https://ouranos.mareo.fr:7443
                  accessKeyId: ${AWS_ACCESS_KEY_ID}
                  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
                  region: ceph
                  s3ForcePathStyle: true
                schemaConfig:
                  - from: "2024-01-01"
                    store: tsdb
                    object_store: s3
                    schema: v12
                    indes:
                      prefix: loki_index_
                      period: 24h
            write:
              replicas: 1
              affinity: ""
              extraArgs:
                - "-config.expand-env=true"
              extraEnvFrom:
                - secretRef:
                    name: loki-s3-creds
            read:
              replicas: 1
              affinity: ""
              extraArgs:
                - "-config.expand-env=true"
              extraEnvFrom:
                - secretRef:
                    name: loki-s3-creds
            backend:
              replicas: 1
              affinity: ""
              extraArgs:
                - "-config.expand-env=true"
              extraEnvFrom:
                - secretRef:
                    name: loki-s3-creds

            monitoring:
              dashboards:
                annotations:
                  k8s-sidecar-target-directory: /tmp/dashboards/Loki Dashboards
              lokiCanary:
                enabled: false
              selfMonitoring:
                enabled: false
                grafanaAgent:
                  installOperator: false
            test:
              enabled: false
