---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-redis-password
  namespace: nextcloud
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: nextcloud/redis
---
apiVersion: k8s.amaiz.com/v1alpha1
kind: Redis
metadata:
  name: redis
spec:
  replicas: 3
  redis:
    image: redis:6-alpine
    initialDelaySeconds: 10
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 500Mi
  dataVolumeClaimTemplate:
    metadata:
      name: redis-data
    spec:
      storageClassName: csi-rbd-sc-delete
      resources:
        requests:
          storage: 10Gi
  annotations: {}
  password:
    secretKeyRef:
      name: nextcloud-redis-password
      key: password
