apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-cluster-admin
subjects:
- kind: Group
  name: oidc:kubernetes_admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:cluster-admin
  apiGroup: rbac.authorization.k8s.io
