---
- name: Include SSH tasks
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - ssh
    - openssh

- name: Include packages tasks
  ansible.builtin.import_tasks: packages.yml
  tags:
    - pkg
    - pkgs
    - packages

- name: Include time tasks
  ansible.builtin.import_tasks: time.yml
  tags:
    - time
    - timezone
    - tz

- name: Include confs tasks
  ansible.builtin.import_tasks: confs.yml
  tags:
    - confs
    - dotfiles

- name: Include ubuntu-motd tasks
  ansible.builtin.import_tasks: ubuntu-motd.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include cloud-init tasks
  ansible.builtin.import_tasks: cloud-init.yml
  when: ansible_distribution == 'Ubuntu'
