---
- name: Install aptitude using apt (Debian)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.package:
    name: aptitude
    state: latest  # noqa package-latest
    update_cache: true
    force_apt_get: true

- name: Install default packages (Debian)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.package:
    state: present
    name: "{{ default_packages | default([]) }}"

- name: Install group specific packages
  when: group_packages
  ansible.builtin.package:
    state: present
    name: "{{ group_packages }}"

- name: Install host specific packages
  when: host_packages
  ansible.builtin.package:
    state: present
    name: "{{ host_packages }}"
