# yamllint disable rule:line-length
---
tls:
  enabled: true
  secret:
    name: dovecot-tls

persistence:
  enabled: true
  storageClassName: "csi-rbd-sc-retain"

stats:
  enabled: true

managesieve:
  enabled: true
  starttls: false
  service:
    type: LoadBalancer
    nodePort: 30419

imap:
  enabled: true
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: imap.mareo.fr.
    type: LoadBalancer
    nodePort: 30143
    tlsNodePort: 30993

sasl:
  enabled: true

lmtp:
  enabled: true

plugins:
  quota:
    enabled: true
    vsizes: true

ldap:
  enabled: true
  uris: "ldap://ak-outpost-mail-ldap.authentik.svc"
  base: "dc=mail,dc=mareo,dc=fr"
  dn: "cn=mail-dovecot,ou=users,dc=mail,dc=mareo,dc=fr"
  dnpass:
    secret: dovecot-ldap-credentials
    key: DOVECOT_LDAP_DNPASS
  authBind: true
  filter: "(|(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(mailboxes=%u))(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(cn=%u)))"
  passAttrs:
    - dovecotAclGroups=userdb_acl_groups=%{ldap:dovecotAclGroups}
    - dovecotQuotaStorage=userdb_quota_rule=*:storage=%{ldap:dovecotQuotaStorage}
    - dovecotQuotaStorage=userdb_quota_rule2=*:messages=%{ldap:dovecotQuotaMessages}
  userAttrs:
    - dovecotAclGroups=acl_groups=%{ldap:dovecotAclGroups}
    - dovecotQuotaStorage=quota_rule=*:storage=%{ldap:dovecotQuotaStorage}
    - dovecotQuotaStorage=quota_rule2=*:messages=%{ldap:dovecotQuotaMessages}
  iterateFilter: "(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(mailboxes=*))"
  iterateAttrs: "mailboxes=user"

log:
  auth:
    debug: true
  mail:
    debug: true
  ssl:
    verbose: false
