# yamllint disable rule:line-length
---
kind: Kustomization

commonLabels:
  app: mail

resources:
  - postfix.yml
  - dovecot.yml

configMapGenerator:
  - name: dovecot-config
    literals: []
  - name: opendkim-config
    literals: []
  - name: postfix-config
    literals:
      - "POSTFIX_SMTPD_SASL_PATH=inet:dovecot:113"
      - "POSTFIX_INTERNAL_MAIL_FILTER_CLASSES=bounce"
  - name: postfix-config-files
    files: []
  - name: postsrsd-config
    literals: []

images:
  - name: registry.cri.epita.fr/cri/docker/mail
    newTag: 7d7a9441080e3be7e33428c8909a64d9c76a4ff7
