# yamllint disable rule:line-length
---
kind: Kustomization

commonLabels:
  app: mail

resources:
  - postfix.yml

configMapGenerator:
  - name: opendkim-config
    literals: []
  - name: opendmarc-config
    literals: []
  - name: postfix-config
    literals:
      - "POSTFIX_INTERNAL_MAIL_FILTER_CLASSES=bounce"
      - "POSTFIX_ALIAS_MAPS=hash:/etc/aliases"
  - name: postfix-config-files
    files: []
  - name: postgrey-config
    literals: []
  - name: postsrsd-config
    literals: []

images:
  - name: registry.mareo.fr/services/docker/postfix
    newTag: commit-22a8859c3cbc95a4e1671f91f534b46461dc1fbc
