---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petitstream
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'petitstream'
      server: 'https://kubernetes.default.svc'
    - namespace: 'petitstream-dev'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  roles:
    - name: dev
      description: Full access on development namespace
      policies:
        - p, proj:petitstream:dev, applications, get, petitstream/*, allow
        - p, proj:petitstream:dev, applications, sync, petitstream/petitstream-dev, allow
        - p, proj:petitstream:dev, applications, action/apps/Deployment/restart, petitstream/petitstream-dev, allow
        - p, proj:petitstream:dev, applications, action//Pod/delete, petitstream/petitstream-dev, allow
        - p, proj:petitstream:dev, exec, create, petitstream/petitstream-dev, allow
      groups:
        - argocd_petitstream_devs
        - argocd_petitstream_ops
    - name: ops
      description: Full access on production namespace
      policies:
        - p, proj:petitstream:ops, applications, get, petitstream/petitstream, allow
        - p, proj:petitstream:ops, applications, sync, petitstream/petitstream, allow
        - p, proj:petitstream:ops, applications, action/apps/Deployment/restart, petitstream/petitstream, allow
        - p, proj:petitstream:ops, exec, create, petitstream/petitstream, allow
      groups:
        - argocd_petitstream_ops
