---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.mareo.fr/iac/infrastructure
    targetRevision: HEAD
    path: "k8s/argocd/"
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
