---
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.7
  - applications.yml
  - ingress.yml
  - argocd-oidc.yml

  - apps

patches:
  - path: argocd-cm-patch.yml
  - path: argocd-rbac-cm-patch.yml
