---
kind: Kustomization
namespace: argocd

resources:
  - applications.yml
  - argocd-oidc.yml

  - apps
  - projects
patchesJson6902:
  - target:
      kind: ClusterRole
      name: argocd-server
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - ""
          resources:
            - pods/exec
          verbs:
            - create
