---
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.8
  - applications.yml
  - ingress.yml
  - argocd-oidc.yml

  - apps
  - projects

patches:
  - path: argocd-cm-patch.yml
  - path: argocd-rbac-cm-patch.yml
