---
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.1

  - applications.yml
  - argocd-metrics.yml
  - argocd-oidc.yml
  - ingress.yml

  - apps
  - projects

patches:
  - path: argocd-cm-patch.yml
  - path: argocd-rbac-cm-patch.yml

patchesJson6902:
  - target:
      kind: ClusterRole
      name: argocd-server
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - ""
          resources:
            - pods/exec
          verbs:
            - create
