---
- name: Reload networking
  ansible.builtin.service:
    name: networking
    state: reloaded

- name: Restart radosgw
  ansible.builtin.service:
    name: ceph-radosgw@rgw
    state: restarted

- name: Run dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
