# yamllint disable rule:line-length
---
tls:
  enabled: true
  secret:
    name: dovecot-tls

persistence:
  enabled: true
  storageClassName: "csi-rbd-sc-retain"

stats:
  enabled: true

podAnnotations:
  backup.velero.io/backup-volumes: data

managesieve:
  enabled: true
  starttls: true
  service:
    type: LoadBalancer
    nodePort: 30419

imap:
  enabled: true
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: imap.mareo.fr., mail.mareo.fr., imap.hannache.fr, mail.hannache.fr, mail.theseusformation.fr, imap.theseusformation.fr
    type: LoadBalancer
    nodePort: 30143
    tlsNodePort: 30993

sasl:
  enabled: true

lmtp:
  enabled: true

plugins:
  quota:
    enabled: true
    vsizes: true
  sieve:
    submissionHost: "postfix.mail.svc"
    imapSieve:
      enabled: true
      url: "sieve://imap.mareo.fr"

ldap:
  enabled: true
  uris: "ldap://ak-outpost-mail-ldap.authentik.svc"
  base: "dc=mail,dc=mareo,dc=fr"
  dn: "cn=mail-dovecot,ou=users,dc=mail,dc=mareo,dc=fr"
  dnpass:
    secret: dovecot-ldap-credentials
    key: DOVECOT_LDAP_DNPASS
  authBind: true
  filter: "(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(mailboxes=%u))"
  passAttrs:
    - dovecotAclGroups=userdb_acl_groups=%{ldap:dovecotAclGroups}
    - dovecotQuotaStorage=userdb_quota_rule=*:storage=%{ldap:dovecotQuotaStorage}
    - dovecotQuotaStorage=userdb_quota_rule2=*:messages=%{ldap:dovecotQuotaMessages}
    - mail=userdb_sieve_user_email=%{ldap:mail}
  userAttrs:
    - dovecotAclGroups=acl_groups=%{ldap:dovecotAclGroups}
    - dovecotQuotaStorage=quota_rule=*:storage=%{ldap:dovecotQuotaStorage}
    - dovecotQuotaStorage=quota_rule2=*:messages=%{ldap:dovecotQuotaMessages}
    - mail=sieve_user_email=%{ldap:mail}
  iterateFilter: "(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(mailboxes=*))"
  iterateAttrs: "mailboxes=user"

log:
  auth:
    debug: true
  mail:
    debug: false
  ssl:
    verbose: false

extraVolumeMounts:
  - name: config
    mountPath: /etc/dovecot/args/ext_extra_passdb.yaml
    subPath: ext_extra_passdb.yaml

extraEnv:
  - name: DOVECOT_LDAP_PASSDB_USERNAME_FILTER
    value: "*@*"
  - name: DOVECOT_EXT_EXTRA_PASSDB_DNPASS
    valueFrom:
      secretKeyRef:
        name: "dovecot-ldap-credentials"
        key: DOVECOT_LDAP_DNPASS

configMap:
  data:
    globals.acl: |
      * owner lrwstipekxa
      * group-override=master lrwstipekxa
      Shared/mareo.fr/* group-override=mareo lrwstipekxa
      Shared/theseusformation.fr/root@theseusformation.fr/* group-override=theseus lrwstipekxa
      Shared/theseusformation.fr/contact@theseusformation.fr/* group-override=theseus lrwstipekxa
    extra_passdb.conf: |
      passdb {
        driver = ldap
        args = /etc/dovecot/args/ext_extra_passdb.conf
        skip = authenticated
        username_filter = !*@*
      }
    ext_extra_passdb.yaml: |
      uris: {{ quote .Values.ldap.uris }}
      base: {{ quote .Values.ldap.base }}
      dn: {{ quote .Values.ldap.dn }}
      auth_bind: "yes"
      pass_filter: "(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(cn=%u))"
      pass_attrs: "cn=user=%{ldap:cn}"
