# yamllint disable rule:line-length
---
tls:
  enabled: true
  secret:
    name: dovecot-tls

persistence:
  enabled: true
  storageClassName: "csi-rbd-sc-retain"

stats:
  enabled: true

podAnnotations:
  backup.velero.io/backup-volumes: data

managesieve:
  enabled: true
  starttls: true
  service:
    type: LoadBalancer
    nodePort: 30419

imap:
  enabled: true
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: imap.mareo.fr.
    type: LoadBalancer
    nodePort: 30143
    tlsNodePort: 30993

sasl:
  enabled: true

lmtp:
  enabled: true

plugins:
  quota:
    enabled: true
    vsizes: true
  sieve:
    submissionHost: "postfix.mail.svc"
    imapSieve:
      enabled: true
      url: "sieve://athena.mareo.fr"
    scripts:
      default:
        enabled: true
        name: default
    configMap:
      data:
        default.sieve: |
          require "subaddress";
          require "fileinto";
          require "mailbox";

          #SCRIPTNAME: Script part 0
          if address :all :is "to" "marin@hannache.fr"
          {
            fileinto :create "test";
          }

ldap:
  enabled: true
  uris: "ldap://ak-outpost-mail-ldap.authentik.svc"
  base: "dc=mail,dc=mareo,dc=fr"
  dn: "cn=mail-dovecot,ou=users,dc=mail,dc=mareo,dc=fr"
  dnpass:
    secret: dovecot-ldap-credentials
    key: DOVECOT_LDAP_DNPASS
  authBind: true
  filter: "(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(mailboxes=%u))"
  passAttrs:
    - dovecotAclGroups=userdb_acl_groups=%{ldap:dovecotAclGroups}
    - dovecotQuotaStorage=userdb_quota_rule=*:storage=%{ldap:dovecotQuotaStorage}
    - dovecotQuotaStorage=userdb_quota_rule2=*:messages=%{ldap:dovecotQuotaMessages}
  userAttrs:
    - dovecotAclGroups=acl_groups=%{ldap:dovecotAclGroups}
    - dovecotQuotaStorage=quota_rule=*:storage=%{ldap:dovecotQuotaStorage}
    - dovecotQuotaStorage=quota_rule2=*:messages=%{ldap:dovecotQuotaMessages}
  iterateFilter: "(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(mailboxes=*))"
  iterateAttrs: "mailboxes=user"

log:
  auth:
    debug: true
  mail:
    debug: true
  ssl:
    verbose: false

extraVolumeMounts:
  - name: config
    mountPath: /etc/dovecot/args/ext_extra_passdb.yaml
    subPath: ext_extra_passdb.yaml

extraEnv:
  - name: DOVECOT_EXT_EXTRA_PASSDB_DNPASS
    valueFrom:
      secretKeyRef:
        name: "dovecot-ldap-credentials"
        key: DOVECOT_LDAP_DNPASS

configMap:
  data:
    extra_passdb.conf: |
      passdb {
        driver = ldap
        args = /etc/dovecot/args/ext_extra_passdb.conf
        skip = authenticated
        username_filter = !*@*
      }
    ext_extra_passdb.yaml: |
      uris: {{ quote .Values.ldap.uris }}
      base: {{ quote .Values.ldap.base }}
      dn: {{ quote .Values.ldap.dn }}
      auth_bind: "yes"
      pass_filter: "(&(memberOf=cn=mail,ou=groups,dc=mail,dc=mareo,dc=fr)(cn=%u))"
      pass_attrs: "cn=user=%{ldap:cn}"
