---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dovecot-tls
spec:
  dnsNames:
    - ouranos.mareo.fr
    - mail.mareo.fr
    - imap.mareo.fr
    - imap.hannache.fr
    - mail.hannache.fr
    - imap.theseusformation.fr
    - mail.theseusformation.fr
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: default-issuer
  secretName: dovecot-tls
