---
sshd_port: 2222

proxmox_template_default_storage: rbd

proxmox_ceph_enabled: true
proxmox_ceph_replicas: 2
proxmox_ceph_osds:
  - /dev/nvme0n1p3
  - /dev/nvme1n1p3
proxmox_ceph_pools:
  - name: rbd
    add_to_storages: 1
  - name: kubernetes
proxmox_ceph_rgw_enabled: true

dhcp_global_domain_name_servers:
  - 1.1.1.1
  - 8.8.8.8

dhcp_global_domain_search:
  - vm.ouranos.mareo.fr
  - mareo.fr

dhcp_hosts:
  - name: k3s-1.vm.ouranos.mareo.fr
    hostname: k3s-1.vm.ouranos.mareo.fr
    mac: 0e:a6:7d:72:7e:01
    ip: 192.168.0.1

nft_define_host:
  self:
    name: self
    value: 148.251.4.90
  k3s:
    name: k3s
    value: 192.168.0.1

forwarded_ports:
  - dport: 21027  # syncthing-discovery
    host: $k3s
    port: 21027
    protocol: udp
  - dport: 22000  # syncthing-listen
    host: $k3s
    port: 22000
  - dport: ssh
    host: $k3s
    port: 30022
  - dport: domain
    host: $k3s
    port: 30053
  - dport: domain
    host: $k3s
    port: 30053
    protocol: udp
  - dport: http
    host: $k3s
    port: 30080
  - dport: https
    host: $k3s
    port: 30443
  - dport: 9000 # gitlab-runner-session-server
    host: $k3s
    port: 30093
  - dport: smtp
    host: $k3s
    port: 30025
  - dport: sieve
    host: $k3s
    port: 30419
  - dport: submissions
    host: $k3s
    port: 30465
  - dport: submission
    host: $k3s
    port: 30587
  - dport: imaps
    host: $k3s
    port: 30993
  - dport: 6443
    host: $k3s

  # vrising
  - dport: 9876
    port: 32318
    host: $k3s
    protocol: udp
  - dport: 9877
    port: 31101
    host: $k3s
    protocol: udp

  # factorio
  - dport: 34197
    host: $k3s
    protocol: udp

  - dport: 30100
    host: $k3s

# yamllint disable rule:line-length
nft_input_host_rules:
  050 accept ssh:
    - tcp dport {{ sshd_port }} accept
nft_forward_host_rules: "{{ nft_forward_host_rules_yaml | from_yaml }}"
nft__nat_host_prerouting_rules: "{{ nft__nat_host_prerouting_rules_yaml | from_yaml }}"

nft__custom_content: |
  #jinja2: lstrip_blocks: "True", trim_blocks: "True"
  table ip nat {
    chain output {
      # 000 policy
      type nat hook output priority 0;
      {% for comment, rules in nft__nat_host_prerouting_rules_yaml | from_yaml | dictsort %}
      # {{ comment }}
      {% for rule in rules %}
      {{ rule }}
      {% endfor %}
      {% endfor %}
    }
  }

nft_forward_host_rules_yaml: |
  "200 port forwarding":
  {% for fwd in forwarded_ports %}
    - ip daddr {{ fwd.host }} {{ fwd.protocol | default('tcp') }} dport {{ fwd.port | default(fwd.dport) }} accept
  {% endfor %}

nft__nat_host_prerouting_rules_yaml: |
  "200 port forwarding":
  {% for fwd in forwarded_ports %}
    - ip daddr $self {{ fwd.protocol | default('tcp') }} dport {{ fwd.dport }} dnat to {{ fwd.host }}:{{ fwd.port | default(fwd.dport) }}
  {% endfor %}

nft__nat_host_output_rules_yaml: |
  "200 port forwarding":
  {% for fwd in forwarded_ports %}
    - ip daddr $self {{ fwd.protocol | default('tcp') }} oif lo dport {{ fwd.dport }} dnat to {{ fwd.host }}:{{ fwd.port | default(fwd.dport) }}
  {% endfor %}
# yamllint enable rule:line-length
