---

- hosts: k3s
  roles:
    - role: xanmanning.k3s
  tasks:
    - name: Create kubeconfig symlink
      when: k3s_control_node is defined and k3s_control_node
      file:
        src: /etc/rancher/k3s/k3s.yaml
        path: ~/.kube/config
        state: link
    - name: Fetch kubeconfig file
      when: k3s_control_node is defined and k3s_control_node
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../secrets/kubeconfig
        fail_on_missing: true
        flat: true
  tags:
    - k3s

- hosts: k3s
  roles:
    - role: mareo.argocd
      when: k3s_control_node is defined and k3s_control_node
  tags:
    - argocd
