---
- name: Gather facts
  hosts: all
  gather_facts: true
  tags:
    - always
    - gather_facts

- name: Run common playbook
  ansible.builtin.import_playbook: common.yml

- name: Run proxmox playbook
  ansible.builtin.import_playbook: proxmox.yml

- name: Run k3s playbook
  ansible.builtin.import_playbook: k3s.yml
