---
- name: Install proxmox
  hosts: proxmox
  roles:
    - mareo.proxmox
  tags:
    - proxmox

- name: Fetch rgw users secret files
  hosts: proxmox
  tasks:
    - name: Fetch rgw user secret file for {{ item.uid }}
      ansible.builtin.fetch:
        src: /etc/ceph/rgw_user_{{ item.uid }}.yml
        dest: ../secrets/rgw_user_{{ item.uid }}.yml
        fail_on_missing: true
        flat: true
      loop: "{{ proxmox_ceph_rgw_users }}"
  tags:
    - secrets
    - proxmox

- name: Set up firewall
  hosts: proxmox
  tasks:
    - name: Blacklist iptables modules
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/blacklist-xtables.conf
        line: install {{ item }} /bin/false
        create: true
        mode: "0644"
      loop:
        - x_tables
        - iptable_nat
        - ip6table_nat
  roles:
    - ipr-cnrs.nftables
  tags:
    - proxmox
    - nftables

- name: Set up DHCP
  hosts: proxmox
  roles:
    - bertvv.dhcp
  tags:
    - proxmox
    - dhcp
