# yamllint disable rule:line-length
---
kind: Kustomization
namespace: mail

resources:
  - namespace.yml
  - ../../../apps/mail/

  - certificate.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: opendkim-config
    behavior: merge
    literals:
      - "OPENDKIM_DOMAIN=csl:hannache.fr,mareo.fr,ouranos.mareo.fr,auth.mareo.fr,documents.mareo.fr,gitlab.mareo.fr,grafana.mareo.fr,theseusformation.fr,nextcloud.mareo.fr,vaultwarden.mareo.fr"
      - "OPENDKIM_SELECTOR=ouranos"
      - "OPENDKIM_SUBDOMAINS=no"
      - "OPENDKIM_KEYFILE=/secrets/opendkim/ouranos"
      - "OPENDKIM_MACROLIST=csl:{dkimsign}=yes,dkimsign=yes"
  - name: postfix-config
    behavior: merge
    literals:
      - "LDAP_SERVER_HOST=ldap://ak-outpost-mail-ldap.authentik.svc"
      - "LDAP_SEARCH_BASE=dc=mail,dc=mareo,dc=fr"
      - "POSTFIX_MYHOSTNAME=ouranos.mareo.fr"
      - "POSTFIX_MYDOMAIN=mareo.fr"
      - "POSTFIX_MYDESTINATION=$myhostname"
      - "POSTFIX_MYNETWORKS=127.0.0.0/8, [::1/128]"
      - "POSTFIX_SMTPD_CLIENT_RESTRICTIONS=permit_mynetworks, permit_sasl_authenticated, reject_unknown_reverse_client_hostname"
      - "POSTFIX_SMTPD_RELAY_RESTRICTIONS=permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination"
      - "POSTFIX_SMTPD_RECIPIENT_RESTRICTIONS=permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, check_policy_service unix:private/policyd-spf, permit_dnswl_client list.dnswl.org, check_recipient_access hash:/etc/postfix/recipient_access.hash, check_policy_service inet:127.0.0.1:10023"
      - "POSTFIX_SMTPD_SENDER_RESTRICTIONS=permit_mynetworks, reject_sender_login_mismatch"
      - "POSTFIX_SMTPD_SENDER_LOGIN_MAPS=ldap:/etc/postfix/sender_login_user.ldap"
      - "POSTFIX_SMTPD_TLS_ASK_CCERT=yes"
      - "POSTFIX_SMTP_DNS_SUPPORT_LEVEL=dnssec"
      - "POSTFIX_SMTP_TLS_SECURITY_LEVEL=dane"
      - "POSTFIX_MILTER_MACRO_DEFAULTS=dkimsign=yes"
      - "POSTFIX_VIRTUAL_TRANSPORT=lmtp:inet:dovecot-lmtp.mail.svc"
      - "POSTFIX_VIRTUAL_MAILBOX_DOMAINS=mareo.fr, hannache.fr, documents.mareo.fr, gitlab.mareo.fr, theseusformation.fr"
      - "POSTFIX_VIRTUAL_ALIAS_MAPS=hash:/etc/postfix/virtual_alias_maps.hash unionmap:{pipemap:{ldap:/etc/postfix/virtual_alias_maps_rules.ldap,pcre:/etc/postfix/virtual_alias_maps_rules.pcre},ldap:/etc/postfix/virtual_alias_maps.ldap} ldap:/etc/postfix/virtual_alias_maps_mailboxes.ldap"
      - "POSTFIX_SMTPD_SASL_PATH=inet:dovecot-sasl.mail.svc:113"
      - "POSTFIX_SMTPD_TLS_CAPATH=/etc/ssl/certs/"
      - "POSTFIX_SMTPD_TLS_CAFILE=/etc/ssl/certs/ca-certificates.crt"
      - "POSTFIX_SMTP_TLS_CAPATH=/etc/ssl/certs/"
      - "POSTFIX_SMTPD_TLS_RECEIVED_HEADER=yes"
      - "POSTFIX_MESSAGE_SIZE_LIMIT=52428800"
      - "POSTFIX_SENDER_CANONICAL_MAPS="
      - "POSTFIX_RECIPIENT_CANONICAL_MAPS="
  - name: postfix-config-files
    behavior: merge
    files:
      - config/recipient_access.hash
      - config/sender_login_user.ldap
      - config/virtual_alias_maps.hash
      - config/virtual_alias_maps.ldap
      - config/virtual_alias_maps_mailboxes.ldap
      - config/virtual_alias_maps_rules.ldap
      - config/virtual_alias_maps_rules.pcre
  - name: postgrey-config
    behavior: merge
    literals:
      - "POSTGREY_HOSTNAME=ouranos.mareo.fr"
  - name: postsrsd-config
    behavior: merge
    literals:
      - "POSTSRSD_DOMAIN=mareo.fr"

patches:
  - target:
      kind: StatefulSet
      name: postfix
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: postfix-secret
