# yamllint disable rule:line-length
---
kind: Kustomization
namespace: mail

resources:
  - namespace.yml
  - ../../../apps/mail/

  - certificate.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: opendkim-config
    behavior: merge
    literals:
      - "OPENDKIM_DOMAIN=mareo.fr"
      - "OPENDKIM_SELECTOR=athena"
      - "OPENDKIM_SUBDOMAINS=yes"
      - "OPENDKIM_KEYFILE=/secrets/opendkim/athena"
      - "OPENDKIM_MACROLIST=csl:{dkimsign}=yes,dkimsign=yes"
  - name: postfix-config
    behavior: merge
    literals:
      - "LDAP_SERVER_HOST=ldap://ak-outpost-mail-ldap.authentik.svc"
      - "LDAP_SEARCH_BASE=dc=mail,dc=mareo,dc=fr"
      - "POSTFIX_MYHOSTNAME=athena.mareo.fr"
      - "POSTFIX_MYDOMAIN=mareo.fr"
      - "POSTFIX_MYDESTINATION="
      - "POSTFIX_MYNETWORKS=127.0.0.0/8, [::1/128], 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
      - "POSTFIX_SMTPD_RELAY_RESTRICTIONS=permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination"
      - "POSTFIX_SMTPD_SENDER_RESTRICTIONS=permit_mynetworks, reject_sender_login_mismatch"
      - "POSTFIX_SMTPD_SENDER_LOGIN_MAPS=ldap:/etc/postfix/sender_login_user.ldap"
      - "POSTFIX_SMTPD_TLS_ASK_CCERT=yes"
      - "POSTFIX_MILTER_MACRO_DEFAULTS=dkimsign=yes"
      - "POSTFIX_VIRTUAL_TRANSPORT=lmtp:inet:dovecot-lmtp.mail.svc"
      - "POSTFIX_VIRTUAL_MAILBOX_DOMAINS=mareo.fr, hannache.fr, gitlab.mareo.fr"
      - "POSTFIX_VIRTUAL_ALIAS_MAPS=unionmap:{pipemap:{ldap:/etc/postfix/virtual_alias_maps_rules.ldap,pcre:/etc/postfix/virtual_alias_maps_rules.pcre},ldap:/etc/postfix/virtual_alias_maps.ldap} ldap:/etc/postfix/virtual_alias_maps_mailboxes.ldap"
      - "POSTFIX_SMTPD_SASL_PATH=inet:dovecot-sasl.mail.svc:113"
      - "POSTFIX_SMTPD_TLS_CAPATH=/etc/ssl/certs/"
      - "POSTFIX_SMTPD_TLS_CAFILE=/etc/ssl/postfix/ca-certificates.pem"
      - "POSTFIX_SMTP_TLS_CAPATH=/etc/ssl/certs/"
      - "POSTFIX_SMTPD_TLS_RECEIVED_HEADER=yes"
  - name: postfix-config-files
    behavior: merge
    files:
      - config/sender_login_user.ldap
      - config/virtual_alias_maps.ldap
      - config/virtual_alias_maps_mailboxes.ldap
      - config/virtual_alias_maps_rules.ldap
      - config/virtual_alias_maps_rules.pcre
  - name: postsrsd-config
    behavior: merge
    literals:
      - "POSTSRSD_DOMAIN=mareo.fr"

patches:
  - target:
      kind: StatefulSet
      name: postfix
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: postfix-secret
