---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opendkim-keys
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: mail/opendkim
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postsrsd-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: mail/postsrsd
