# yamllint disable rule:line-length
---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  annotations:
    external-dns.alpha.kubernetes.io/hostname: smtp.mareo.fr, smtp.hannache.fr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    component: postfix
  ports:
    - name: postfix-smtp
      port: 25
      nodePort: 30025
      targetPort: smtp
      protocol: TCP
    - name: postfix-smtps
      port: 465
      nodePort: 30465
      targetPort: smtps
      protocol: TCP
    - name: postfix-submission
      port: 587
      nodePort: 30587
      targetPort: submission
      protocol: TCP
