---
- name: Check whether app {{ item.key }} is deployed
  ansible.builtin.command:
    argv:
      - argocd
      - --port-forward-namespace
      - "{{ argocd_namespace }}"
      - --port-forward
      - app
      - get
      - "{{ item.key }}"
  register: app_check
  check_mode: false
  changed_when: false
  failed_when: false

- name: Add app
  when: app_check.rc != 0
  block:
    - name: Construct command argv
      ansible.builtin.set_fact:
        command_argv:
          - argocd
          - --port-forward-namespace
          - "{{ argocd_namespace }}"
          - --port-forward
          - app
          - create
          - "{{ item.key }}"
        command_extra_argv: |
          {% for arg in item.value | dict2items %}
          - "--{{ arg.key | replace('_', '-') }}"
          {% if arg.value is string %}
          - "{{ arg.value }}"
          {% endif %}
          {% endfor %}
    - name: Add app {{ item.key }}
      ansible.builtin.command:
        argv: "{{ command_argv + command_extra_argv | from_yaml }}"
      changed_when: true
