---
- name: Install role dependency
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present

- name: Download helm
  ansible.builtin.get_url:
    url: "{{ helm_bin_url }}"
    dest: "/tmp/helm-{{ helm_version }}.tar.gz"
    checksum: "{{ helm_bin_checksum }}"
    mode: 0600

- name: Unarchive helm
  ansible.builtin.unarchive:
    src: "/tmp/helm-{{ helm_version }}.tar.gz"
    dest: "{{ helm_bin_dir }}"
    include:
      - "linux-amd64/helm"
    extra_opts:
      - --strip-components=1
    remote_src: yes

- name: Deploy ArgoCD
  ansible.builtin.include_tasks: argocd.yml

- name: Add apps to ArgoCD
  ansible.builtin.include_tasks: app.yml
  with_dict: "{{ argocd_apps }}"
