---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-secrets-operator
  labels:
    app: vault-secrets-operator
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-vault-secrets-operator"
      labels:
        app: vault-secrets-operator
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{name}}"
        namespace: vault-secrets-operator
      source:
        repoURL: https://ricoberger.github.io/helm-charts
        chart: vault-secrets-operator
        targetRevision: 1.18.0
        helm:
          values: |
            fullnameOverride: vault-secrets-operator
            vault:
              authMethod: kubernetes
              reconciliationTime: 60
              address: https://vault.cri.epita.fr
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: vaultsecrets.ricoberger.de
          jsonPointers:
            - /metadata/labels
